# Analysis and response

## Input data

Input data to the stock assessment are summarized in Table \@ref(tab:data-input).
Relative to the previous assessment, the only change made to input data was to update the time series to include data from the `r this_season` herring season (July 1 to June 30).
Note that we refer to 'year' instead of 'herring season' in this report;
therefore `r assess_yr` refers to the `r this_season` Pacific Herring season.

### Catch data

<!-- TODO: What is "fishing category" in the following sentence? -->
For the purposes of stock assessment, catch data are summarized by gear type and fishing category as described in Table \@ref(tab:data-input) and presented in Figure \@ref(fig:major-catch).
As in previous years, catch input to the stock assessment model does not include mortality from the commercial SOK fishery, nor any recreational fisheries or food, social, and ceremonial (FSC) harvest.
The FSC and recreational harvest are considered minor relative to commercial harvest.
The commercial SOK fishery is licensed based on pounds of validated SOK product (i.e., eggs adhered to kelp), not tonnes of fish used or spawned.
Currently there is no basis for validating mortality imposed on the population by this fishery, however methods for estimating SOK mortality are being developed.

Combined commercial removals from `r assess_yr-9` to `r assess_yr` from the roe, food and bait, and special use fisheries appear in Table \@ref(tab:annual-catch).
The proportion of coast-wide catch that comes from the SoG was 22% in 1990, and nearly 100% in `r assess_yr`.
Total SOK harvest or the major SARs from `r assess_yr-9` to `r assess_yr` is presented in Table \@ref(tab:annual-sok-catch).

### Biological data

Biological samples are collected as described in @cleary2018 and Table \@ref(tab:data-input).
Biological data inputs to the stock assessment are annual weight-at-age (Figure \@ref(fig:major-wa)) and 
annual numbers-at-age, shown as proportions-at-age (Figure \@ref(fig:major-pa)).

Significant declines in weight-at-age are evident for all major herring stocks, from the mid-1980s to 2010.
Declining weight-at-age may be attributed to any number of factors, including fishing effects (i.e., gear selectivity), environmental effects (e.g., changes in ocean productivity), or changes in sampling protocols (e.g., shorter time frame over which samples are collected).
There has been an increasing trend in weight-at-age for all major stocks from 2012 to `r assess_yr`, although to a lesser degree for PRD.

### Abundance data

The surface (`r surv_yr_rng[1]` to `r new_surv_yr - 1`) and dive (`r new_surv_yr` to `r surv_yr_rng[2]`) spawn survey methods involve collecting information on spawn length (parallel to shore), spawn width (perpendicular to shore), number of egg layers by vegetation type, and other data.
These data are used to calculate egg densities per spawn.
Ultimately, the estimated weight of mature spawners required to produce the egg deposition is calculated and referred to as the 'spawn index'.
Execution of the `r surv_yr_rng[2]` spawn survey followed all standard protocols as described in @cleary2018.
Time series of spawn index by major stock assessment region, from `r paste(surv_yr_rng, collapse=" to ")` are summarized in Figure \@ref(fig:major-spawn-index).
In `r surv_yr_rng[2]`, there was a decrease in survey biomass in SoG and WCVI (Figure \@ref(fig:major-spawn-index) and Tables \@ref(tab:spawn-index-sog) & \@ref(tab:spawn-index-wcvi)), and
an increase in survey biomass in HG, PRD, and CC (Figure \@ref(fig:major-spawn-index) and Tables \@ref(tab:spawn-index-hg), \@ref(tab:spawn-index-prd), & \@ref(tab:spawn-index-cc)).

## Spatial spawn distribution

Tables \@ref(tab:spawn-index-hg) through \@ref(tab:spawn-index-wcvi) summarize the spatial distribution of survey spawn biomass (i.e., the spawn index) by proportion over the most recent 10 years for the major SARs.
HG and SoG are summarized by Group, while PRD, CC, and WCVI are summarized by Statistical Area;
the choice of spatial grouping reflects spawning behaviour and biology for each SAR based on the survey data and working group discussions with local First Nations.
Statistical Areas, Sections, and Groups are not intended to represent sub-stock structure or ‘known’ stocklets.

## First Nations observations

Local observations from 2019 were provided by First Nations participants in the Herring Technical Working Group.
This working group, established in 2016, consists of DFO Science and Fisheries Management and technical representatives nominated by numerous coastal First Nations and the herring industry.
Observations reported here describe local perspectives on Pacific Herring in four of the management areas.

<!-- ### Haida Gwaii - not provided in 2019 -->

### Prince Rupert District

Observations from the Lax Kw’alaams Band: This year in the Prince Rupert District, Lax Kw’alaams had several fishermen out on the water.
Overall, very little spawning was observed this season, and what was observed was non-contiguous and with much fewer layers than observed in previous years.
Fishermen reported observing isolated pockets of herring in Tuck Inlet schooling in the area for a few days and then disappearing (north of Prince Rupert, Section 042).
There were also humpback whales observed feeding in the Inlet, possibly causing the herring to move to deeper water to avoid predation and to spawn.
Lax Kw’alaams fishermen were unable to gather enough herring to satisfy FSC needs for the community.
Lax Kw’alaams Fisheries Technicians spent a full seven days during herring season, monitoring harvest and recording herring behaviour and locations.
Technicians were unable to locate herring schools in any of the normal geographic areas monitored each year.
On-grounds correspondence with harvesters confirmed the 2019 season was very poor and most reported seeing no active herring spawning.

### Central Coast

For Klemtu area including Area 6, the spawn was much earlier than in past few years.
The timing corresponds to what would be considered normal timing of a generation ago, with spawn occurring from March 19^th^–-25^th^.
The spawn was relatively long in duration based on previous years, and appeared to cover much of Kitasu Bay, however, the spawn was patchy.
While some spawn in Kitasu Bay was quite thick, most was only a few layers of eggs deposited.
Meyers and Thistle Pass showed relatively strong spawn, better than recent years.
The East Higgins spawn continues to be poor, with only a single small bay experiencing any spawn.
Spawn in Clifford Bay appeared to be limited to the outer island and northern reach.
West Aristazabal was generally low, though storm force winds resulted in a reduced presence/observation on West Aristazabal and Clifford Bay in 2019.

### Strait of Georgia

Observations from Q'ul-lhanumutsun Aquatic Resources Society: No herring spawn was observed south of Dodd Narrows in 2019.

The Tla'amin Nation report observing a very minimal spawning activity in Powell River in 2019.
A single very light spawn occurred in Okeover Inlet with herring eggs occurring on the rocks and seaweed along the beach.

### West Coast of Vancouver Island

As in most years, small spawning events occurred in Hesquiaht Harbour (Area 24) in January and February, and some February spawning in Areas 23 and 25.
The main spawning events in all areas were from early to mid-March.
Nuu-chah-nulth assessment crews found unspawned herring in the eastern part of Area 23 in late March, and a small spawn was reported in early April in Area 23.
'Sporadic' was the term most people used to describe herring spawn activity in 2019.

Most spawning events did not cover large areas and were less than a day in duration.
The exceptions were multi-day spawns around Stuart Bay and Ittatsoo in Area 23 beginning on March 8^th^, and in Hesquiaht Harbour around Anton Spit beginning on March 5^th^.
There were multiple spawning locations in Area 25 including Nuchatlaht, Esperanza Inlet, Yuquot, and Strange Island.
Most were small as well, but there were some larger events in a couple of areas, notably around Strange Island, Rosa Island, and Bajo Reef.

Nuu-chah-nulth harvesters set whole trees and lines of tree branches to harvest herring spawn on bough.
Trees and boughs were set in both usual herring spawning locations, and in active spawning locations in Barkley Sound (Area 23), Clayoquot Sound (Area 24), Nootka Sound, Esperanza Inlet, and Nuchatlitz (Area 25).
Herring spawn on bough harvests were similar to 2018, mixed.
In some areas, some trees had 4--10 layers on the branches, but most had only 1--4 layers.
Despite the efforts, the herring spawn on bough harvests were not sufficient to meet the requests from Nuu-chah-nulth communities.

## Stock status update

Analyses of stock trend information for AM2 are presented following methods of @cleary2018 for the Pacific Herring major stock assessment regions.
Perceptions of stock status based on outputs from the SCA model (AM2) are summarized for each stock in a multi-panel figure (e.g., Figure \@ref(fig:storyboard-hg)).
The panels \ref{item:storyIndex} to \ref{item:storyPhase} show:

(a) Time series of model fit to scaled spawn survey data,\label{item:storyIndex}

(a) Time series of instantaneous natural mortality rate $M$ estimates,

(a) Time series reconstruction of number of age-2 recruits,

(a) Time series of estimated spawning biomass $\SB_t$ and total catch $C_t$ in year $t$,
with reference lines at model estimates of $0.3\SB_0$,

(a) Time series of (log) deviations from the estimated Beverton-Holt recruitment function, and

(a) Phase plot of spawning biomass production ($\frac{\SB_{t+1} - \SB_t + C_{t+1}}{\SB_t}$) for the dive survey period,
with reference lines at model estimates of $0.3\SB_0$.\label{item:storyPhase}

Note that spawn survey data (i.e., spawn index) is scaled to abundance in panel \ref{item:storyIndex} by the spawn survey scaling parameter $q$.
The spawn index has two distinct periods defined by the dominant survey method: 
surface surveys (`r surv_yr_rng[1]` to `r new_surv_yr-1`), and 
dive surveys (`r new_surv_yr` to `r surv_yr_rng[2]`).
Thus, two $q$ parameters are implemented in the estimation procedure:
$q_1$ (`r surv_yr_rng[1]` to `r new_surv_yr-1`) with an uninformative prior, and
$q_2$ (`r new_surv_yr` to `r surv_yr_rng[2]`) with an informative prior approximating 1.0.

### Reference points\label{sec:ref-pts}

A biological limit reference point (LRP) is defined for the major Pacific Herring SARs at $0.3\SB_0$ [@kronlund2017].
Candidate upper stock references (USR) were introduced in @cleary2018 and implemented as biomass objectives in the simulation analyses for WCVI and SoG in 2018 [@dfo2019a] and then for HG, PRD, and CC in 2019 [@dfo2019c].
Candidate USRs are:

1. $0.4\SB_0$,

1. $0.6\SB_0$,

1. Average spawning biomass from `r major_start_yr` to `r assess_yr`, $\SB_{\mli{ave}}$, and

1. Average spawning biomass during a productive period [@cleary2018], $\SB_{\mli{ave-prod}}$.

Simulation results showed similar properties between USRs $0.6\SB_0$ and $\SB_{\mli{ave}}$ both within and among SARs,
while the USR based on the average biomass in a productive period, $\SB_{\mli{ave-prod}}$, was found to be most variable among SARs.
The simulation-evaluations did not select a single USR,
however a USR of $0.6\SB_0$ is included in this stock status update because this candidate is sufficiently above the LRP (2*LRP) and it is a repeatable calculation across all SARs.
Stock status relative to the assessment model estimates $0.3\SB_0$ (LRP) and $0.6\SB_0$ (USR) are presented for each SAR in Tables \@ref(tab:ref-points-hg) through \@ref(tab:ref-points-wcvi).

The LRP and USR relate stock status to the DFO PA Framework [@dfo2009], and in the assessment of Pacific Herring the same calculations are applied for each SAR.
There is an important distinction between reference points (e.g., LRP, USR) and
the operational control points of the harvest control rule (HCR) or the management procedure used to set catch limits.
Specifically, operational control points (OCPs) define the inflection points of a HCR, and identify biomass levels where management action is taken. For example, the harvest rate is set to zero and fishing ceases when biomass falls below the lower OCP.

### Haida Gwaii

Estimated spawning biomass declined to near historic lows in the mid-1990s and briefly increased through the late 1990s before falling to persistent historic lows from 2000 to 2010 (Figure \@ref(fig:storyboard-hg)d).
A modest increase in estimated spawning biomass occurred during the early 2010s before falling once again to near historic lows over the most recent few years.
The increase can be attributed to increases in the spawn index in 2013 and 2015 (Figure \@ref(fig:storyboard-hg)a) that were supported by above average recruitment of age-2 fish in 2012 (Figure \@ref(fig:storyboard-hg)c, d).
An increasing trend in the estimated natural mortality rate since 1980 (Figure \@ref(fig:storyboard-hg)b) largely absorbed surplus production attributable to above average recruitment events (e.g., 1997 and 2012; Figure \@ref(fig:storyboard-hg)c, d).
In particular, estimated natural mortality has increased sharply since the early 2010s following a decline from a peak rate in the early 2000s.
Since 2000, the HG stock has been in a low biomass state, with many of these years also showing low productivity which has precluded stock growth (Figure \@ref(fig:storyboard-hg)f).
The most recent year, between 2018 and 2019, biomass remains very low and there is evidence of positive productivity.
The effective harvest rate $U_t$ since 2000 has been at or near zero (Figure \@ref(fig:harvest-rate)), with the last commercial roe fishery in 2002, and the last commercial SOK fishery in 2004.

Estimated spawning biomass in `r assess_yr` is `r f(hg_final_yr_sbt[2])`&nbsp;t (`r paste0("$\\SB_{", assess_yr, "}$")`, median posterior value) or 30% of $\SB_0$ (Tables \@ref(hg-spawning-biomass-depletion-table) & \@ref(tab:ref-points-hg)).
Spawning biomass in `r assess_yr` is estimated to be at the LRP of $0.3\SB_0$ with a `r f((1-hg_prob_less_03sbo) * 100, 1)`% probability (Table \@ref(tab:ref-points-hg)).

### Prince Rupert District

Estimated spawning biomass recovered by the mid-1980s from historic low depletion levels following the collapse of the 1960s,
to about 50% of the historic high biomass estimated in the early 1960s (Figure \@ref(fig:storyboard-prd)d).
However, after the mid-1980s, estimated spawning biomass steadily declined before stabilizing at a relatively low level (but above historic lows) by the mid-2000s.
The estimated stock biomass has shown little trend from 2005 to 2018, with a modest increase in 2019.
Fluctuations in the trend in spawning biomass appear to be less than those observed in other SARs,
possibly because some spawn index points are being under- or over-fit (e.g., 2001–2004, 2010-2013) as shown in Figure \@ref(fig:storyboard-prd)a.
Estimated natural mortality reached historic highs in the late 1960s, before declining through the late 1970s.
Beginning in about 1980, estimated natural mortality increased through to `r assess_yr`, roughly doubling from 0.25 to 0.5&nbsp;$\text{yr}^{-1}$ (Figure \@ref(fig:storyboard-prd)b).
This trend in natural mortality coincides with the decline in spawning biomass (Figure \@ref(fig:storyboard-prd)d);
recruitment deviations have fluctuated around 0 without any strong positive or negative trends (Figure \@ref(fig:storyboard-prd)e).
An above average age-2+ recruitment in 2014, 2017-2019, and an increase in the spawn index in the last year were still not sufficient to lead to an increasing trend in biomass (Figure \@ref(fig:storyboard-prd)f).
Commercial catches from 2007-2018 have remained low (below 2,000&nbsp;t) and there was no commercial catch in 2019.
The estimated natural mortality appears to be unchanged from last year,
resulting in what appears to be a small increase in production.
An increasing trend in weight-at-age has been observed since about 2010,
although the change does not appear to be as large as in the HG, CC, SoG and WCVI SARs.

The model estimates spawning biomass in `r assess_yr`, `r paste0("$\\SB_{", assess_yr, "}$")`, at `r f(prd_final_yr_sbt[2])`&nbsp;t (posterior median),
equal to 38.9% of $\SB_0$ (Tables \@ref(prd-spawning-biomass-depletion-table) & \@ref(tab:ref-points-prd)).
Commercial fisheries have occurred annually in PRD since the mid-1980s, with the exception of 2019, during which the effective harvest rate $U_t$ was estimated to be at or below 20% (Figure \@ref(fig:harvest-rate)) in all years except 1989.
Spawning biomass in `r assess_yr` is estimated to be greater than the LRP of $0.3\SB_0$ with a `r f((1-prd_prob_less_03sbo) * 100, 1)`% probability (Table \@ref(tab:ref-points-prd)).

### Central Coast

Estimated spawning biomass fluctuated around a strongly declining trend from a historic high around 1980
before reaching a historic low level in the late 2000s (Figure \@ref(fig:storyboard-cc)d).
An increase in spawning stock biomass was estimated through the mid-2010s
but remained below levels estimated prior to 2000, and then declining modestly 2016-2018.
In 2019 there was an increase in estimated spawning biomass.
The estimated biomass trend largely reflects the trend in the spawn index (Figure \@ref(fig:storyboard-cc)a),
where fluctuations correspond opposite to the fluctuations in estimated natural mortality (Figure \@ref(fig:storyboard-cc)b).
For example, the decline in spawn index (and estimated spawning biomass) to the historic lows of the late 2000s followed a strongly increasing trend in estimated natural mortality through the same period.
Estimated natural mortality moderated by the late 2000s, which was followed by the increase in spawn index (and estimated spawning biomass) until 2015 whereupon natural mortality again increased.
Recruitment deviations were slightly negative (lower than predicted by the stock-recruitment function) on average from about 1990 to 2017,
and have increased to above average in 2018 and 2019 (Figure \@ref(fig:storyboard-cc)e).
In 2019 there is evidence of strong production, similar to the 1990 to 1999 period (Figure \@ref(fig:storyboard-cc)f);
however, the biomass state is not nearly as high as was seen during that period.

A fixed cutoff HCR was implemented in 1986, and from 1986-2007 the effective harvest rate $U_t$ is estimated to fluctuate above and below the `r target_hr*100`% target rate, with median estimates exceeding `r target_hr*100`% frequently (Figure \@ref(fig:harvest-rate)).
Occurrences of $U_t$ exceeding the `r target_hr*100`% target harvest rate are due in part to
positive assessment model errors, and
lags in detecting a directional change in the trend.

Following a commercial fishery closure from 2007 to 2013, the CC stock reopened to commercial fisheries in 2014,
and small commercial roe fisheries occurred in 2014, 2015, and 2016.
A commercial SOK fishery has operated yearly since 2014,
however these removals are not included in the estimation of $U_t$.

The model estimates spawning biomass in `r assess_yr`, `r paste0("$\\SB_{", assess_yr, "}$")`, at `r f(cc_final_yr_sbt[2])`&nbsp;t (posterior median), equal to 60.7% of $\SB_0$ (Tables \@ref(cc-spawning-biomass-depletion-table) & \@ref(tab:ref-points-cc)).
Spawning biomass in `r assess_yr` is estimated to be greater than the LRP of $0.3\SB_0$ with a `r f((1-cc_prob_less_03sbo) * 100, 1)`% probability (Table \@ref(tab:ref-points-cc)).

### Strait of Georgia

The estimated spawning biomass for the SoG stock decreased in 2019,
although the uncertainty associated with the last few years of spawning biomass along with the forecast biomass `r paste0("$\\SB_{", assess_yr, "}$")`, is quite large (Figure \@ref(fig:storyboard-sog)d).
There was an increasing trend in estimated spawning biomass from about 2010 to 2016 which coincided with a decline in estimated natural mortality that began in the late 2000s (Figure \@ref(fig:storyboard-sog)b).
The model estimates natural mortality has been increasing since 2016, and has now reached a level last estimated in the early 1970s.
This coincides with the recent decreasing trend in estimated spawning biomass.
The large uncertainty in both spawning biomass and natural mortality estimates in `r assess_yr` may be in part a function of the declining trend in the spawn index starting in 2017
following the increasing trend that began in 2010 (Figure \@ref(fig:storyboard-sog)a).
The model fits an averaged trajectory through the spawn index values of the 2010s and has, to date,
insufficient information to determine whether the decline from 2016 to `r assess_yr` represents a true decline in estimated spawning biomass.
The model estimates above average recruitment in most years from 2010 to `r assess_yr` (Figure \@ref(fig:storyboard-sog)c)
with the recruitment deviations showing especially large recruitment of age-2 fish in 2019 (Figure \@ref(fig:storyboard-sog)e).
The SoG juvenile herring survey reported an increase in abundance of age-0 fish from 2016 to 2017 (Strait of Georgia Juvenile Herring Survey, September 2017, Canadian Manuscript Report of
Fisheries and Aquatic Sciences, unpublished report).
The sampling program targets prespawning aggregations and the assessment assumes 25% of age-2 herring are mature.
The large uncertainty around estimated age-2 recruitment in the terminal year of the time series is a common observation
because these age-2 fish are only partially recruited to the fishing gear.
The estimated 2019 age-2 recruitment will be adjusted by the model next year with the addition of 2020 sample data (i.e., when the 2017 cohort is sampled as age-3s).
Analysis of surplus production shows that for the year between 2018-2019, the SoG SAR is estimated to be in a high production, high biomass state,
similar to 1989, 1990, 2012 and 2016 (Figure \@ref(fig:storyboard-sog)f).

Commercial fisheries have occurred annually in SoG since the early-1970s (following the stock collapse of the late 1960s).
Since implementing the fixed cutoff HCR in 1986, the effective harvest rate $U_t$ is estimated to fluctuate above and below the `r target_hr*100`% target rate,
with median estimates above `r target_hr*100`% in 2005, 2006, and most years between 2013 and 2019 (Figure \@ref(fig:harvest-rate)).
The model estimates spawning biomass in `r assess_yr`, `r paste0("$\\SB_{", assess_yr, "}$")`, at `r f(sog_final_yr_sbt[2])`&nbsp;t (posterior median),
equal to 46.4% of $\SB_0$ (Tables \@ref(sog-spawning-biomass-depletion-table) & \@ref(tab:ref-points-sog)).
Spawning biomass in `r assess_yr` is estimated to be greater than the LRP of $0.3\SB_0$ with a `r f((1-sog_prob_less_03sbo) * 100, 1)`% probability (Table \@ref(tab:ref-points-sog)).

### West Coast of Vancouver Island

The time series of estimated spawning biomass shows a decline from the late 1980s through to a historic low in the 2000s (Figure \@ref(fig:storyboard-wcvi)d).
The low estimated spawning biomass persisted through the 2006 to 2012 period and has since slowly increased to a level similar to that estimated for 2000.
The model reconstruction of spawning biomass closely follows the trajectory of spawn index values (Figure \@ref(fig:storyboard-wcvi)a).
The increase in spawning biomass from 2013 coincides with a decline in estimated natural mortality from a historic high in the late 2000s (Figure \@ref(fig:storyboard-wcvi)b).
Recruitment deviations have been negative (lower than predicted by the stock-recruit function) on average since about 2003 (Figure \@ref(fig:storyboard-wcvi)e),
however the reduction in estimated natural mortality and absence of removals from a commercial fishery appears to be sufficient to offset this below average recruitment of age-2 fish.
The absence of a commercial fishery since 2005 means the realized harvest rate has been near zero for the last 14 years (Figure \@ref(fig:harvest-rate)).
In recent years there has been modest evidence for an increase in production and biomass.
The production estimates in the 2018-2019 year are at a higher spawning biomass level than those estimated during the low production, low biomass period of the last half of the 2000s and early 2010s (Figure \@ref(fig:storyboard-wcvi)f).

The model estimates spawning biomass in `r assess_yr`, `r paste0("$\\SB_{", assess_yr, "}$")`, at `r f(wcvi_final_yr_sbt[2])`&nbsp;t (posterior median),
equal to 44.2% of $\SB_0$ (Tables \@ref(wcvi-spawning-biomass-depletion-table) & \@ref(tab:ref-points-wcvi)).
Spawning biomass in `r assess_yr` is estimated to be greater than the LRP of $0.3\SB_0$ with a `r f((1-wcvi_prob_less_03sbo) * 100, 1)`% probability (Table \@ref(tab:ref-points-wcvi)).

## Management performance

Management procedure performance can be investigated using time series of effective harvest rate.
The estimated effective harvest rate $U$ in each year $t$, calculated as
$U_t = C_t/(C_t + \SB_t)$, where
$C_t$ is catch in year $t$, and
$\SB_t$ is estimated spawning biomass in year $t$.
Times series of $U_t$ relative to target harvest rate of `r target_hr*100`% are presented in Figure \@ref(fig:harvest-rate).

## Application of MPs and harvest options for `r assess_yr + 1`\label{sec:harv-opts}

Generally, harvest advice for the major stocks of Pacific Herring has been based on a 1-year forecast of pre-fishery spawning biomass and
application of a HCR that is a hybrid of fixed escapement and a target harvest rate (e.g., @hall1988).
Although the target harvest rate has varied among regions in recent years (e.g., CC and PRD SARs; @dfo2017),
the “historical” practice was to apply a target harvest rate of `r target_hr*100`%
when the forecast is estimated to be above a fixed commercial fishery cutoff of
$0.25\SB_0$ defined in the 1996 stock assessment [@dfo2016].
This rule is referred to as the "fixed cutoff rule."

Renewal of the Pacific Herring management framework included a commitment to MSE simulation-evaluation of the performance of historical fixed cutoff and
alternative MPs in relation to conservation and fisheries management objectives.
The first cycle of the MSE process was completed for the WCVI and SoG SARs in 2018 [@dfo2019a];
a similar process was used to evaluate harvest strategies for HG, PRD, and CC in 2019 [@dfo2019c].

The ranking of objectives and selection of MPs that meet objectives using MSE is an iterative process.
The first cycle of Pacific Herring MSE includes, as a starting point, four core fisheries management objectives [@dfo2019c] which reflect DFO policy, and were applied to each major SAR:

<!-- TODO: I don't like how this first Objective reads compared to the other three. I know it's copied from the MSE papers, but it's ambiguous. I think it should read "Maintain spawning biomass above the LRP with at least 75%...". -->
1. Avoid the LRP with at least 75% probability over three Pacific Herring generations
(i.e., avoid a biomass limit; $P(\SB_t > 0.3\SB_0) \geq 0.75$),

1. Maintain spawning biomass at or above the USR with at least 50% probability over three Pacific Herring generations
(i.e., achieve a target biomass; $P(\SB_t \geq 0.6\SB_0) \geq 0.5$),

1. Maintain average annual variability (AAV) in catch below 25% over three Pacific Herring generations
(goal reflecting catch variability; $\text{AAV} < 0.25$), and

1. Maximize average annual catch over three Pacific Herring generations
(goal reflecting catch biomass).

However, a fully specified set of objectives has not yet been developed for each management area.
DFO will continue to collaborate with coastal First Nations to develop area-specific objectives specific to Food, Social and Ceremonial fisheries as well as spawn-on-kelp (SOK) fisheries.
In addition, DFO will continue to engage with the herring industry, government, and non-government organizations
to describe broader objectives related to conservation, economics, and access.

The MPs for each SAR differ in the form of the HCR and choices of catch cap, but use the same monitoring data and assessment model [e.g., @cleary2018].
The current assessment model assumes natural mortality is time-varying.
The first MSE cycle introduced three hypotheses about future Pacific Herring natural mortality $M$: 

1. $M$ is a time-varying, density-dependent process (DDM),

1. $M$ is a time-varying, density-independent process (DIM), and

1. $M$ is constant over time (conM).

These three hypotheses are captured as three operating model (OM) scenarios in @dfo2019a.
The DDM scenario was identified as the Reference OM scenario based on discussion at the July 2018 CSAS review process [@dfo2019c],
while the DIM and conM scenarios were identified as Robustness OM scenarios.
There is however currently no correct scientifically supported method for predicting the natural mortality and therefore all three scenarios are included. 

Results presented here represent all three OM scenarios.

Several lessons were learned from the analysis:

1. The catch-at-age stock assessment model can produce large (positive) assessment errors.
Such assessment errors cause over-estimation of spawning biomass and
result in recommended catch limits such that the realized harvest rate exceeds the intended target specified by a HCR (e.g., over-harvest).

1. Reduction in harvest rate from 20% to 10% was the most effective means of mitigating stock assessment errors by reducing the absolute size of the catch.
The use of a catch cap, implemented as a maximum annual catch level, was an effective model-free way to further mitigate assessment errors.
Simulation analyses additionally showed that outcomes are insensitive to the choice of operational control points (OCPs) in the HCR when a low harvest rate (HR) and catch cap are applied.
This occurs because low biomass levels (associated with the lower OCP) are avoided for these management procedures (MPs).

1. Differences in specification of Pacific Herring MPs, including the HCR components, are expected a priori among SARs.
The reasons relate to differences in objectives deemed important by resource users,
differences in historical and current stock and fishery dynamics, and
differences in the magnitude and direction of assessment model errors in each SAR.
Conservation objectives such as those based on avoiding a threshold to serious harm (i.e., a limit reference point) in alignment with the DFO PA Framework [@dfo2009] are held constant among SARs based on the analyses of @kronlund2017.

Harvest options for `r assess_yr+1` reflect application of simulation-tested MPs for each major SAR.

### Haida Gwaii

The HG stock has persisted in a low biomass, low productivity state since 2000.
The stock was below the LRP for much of that period and shows little evidence of sustained stock growth despite the absence of commercial fisheries since 2002 (2004 for the SOK fishery).
In the absence of fishing, spawning biomass in `r assess_yr + 1` is forecast at `r f(hg_proj_sbt[2])`&nbsp;t (posterior median).
Results of the simulation-evaluations found that none of the proposed MPs, 
including the historical and no fishing MPs,
performed satisfactorily against the conservation objective of maintaining spawning biomass above the LRP with high probability
(at least 75%).\footnote{\label{fn:HighProb}``High'' probability is defined as 75 to 95\% by the DFO Decision-making framework (DFO 2009).}
<!-- TODO: automate the citation in the footnote (\citep{dfo2009}) -->

The projected spawning biomass in `r assess_yr + 1` is forecast to be below $0.3\SB_0$ with `r f(hg_prob_proj_less_03sbo * 100, 1)`% probability in the absence of fishing (Table \@ref(tab:ref-points-hg) and Figure \@ref(fig:proj-biomass-density)).

DFO has committed to developing and implementing a rebuilding plan for Haida Gwaii Pacific Herring by the end of fiscal year 2020/21.[^RebuildHG]
Work is underway through a technical working group comprised of members of the Council of Haida Nation, DFO, and Parks Canada.
Guidance for the Development of Rebuilding Plans under the Precautionary Approach Framework: Growing Stocks out of the Critical Zone [@dfo2013] states that
the primary objective of any rebuilding plan is to promote stock growth out of the Critical Zone (i.e., to grow the stock above the status-based LRP) by
ensuring removals from all fishing sources are kept to the lowest possible level until the stock has cleared this zone with high probability.
Stock rebuilding does not end having met this goal, however, and one of the goals of the rebuilding plan will be to
identify candidate threshold biomass levels greater than the LRP that are consistent with a rebuilt state.

[^RebuildHG]: In response to recommendations in the Commissioner of the Environment and Sustainable Development (CESD) October 2016 Report 2 - Sustaining Canada’s Major Fish Stocks - Fisheries and Oceans Canada,
the Department will develop rebuilding plans for major fish stocks that are in the precautionary approach critical zone,
including Haida Gwaii Pacific Herring by the end of fiscal year 2020/21.

DFO supports commercial herring fishery closures for the HG major stock region until April 2021.
As such, the harvest recommendation for the HG stock in `r assess_yr + 1` is 0&nbsp;t.

### Prince Rupert District

For PRD the best performing MPs generally had 10% or lower harvest rates, although two MPs with a 20% harvest rate did meet the conservation objective because they use a higher lower OCP (see Section '\nameref{sec:ref-pts}') of $0.5\SB_0$.
These MPs also result in more frequent fishery closures due to spawning biomass declined below the lower control point more frequently.
While several MPs are able to meet core conservation objective of maintaining spawning
biomass above the LRP with high probability (at least 75%)^\ref{fn:HighProb}^,
they also imply different trade-offs among biomass (e.g., ecosystem) and yield outcomes.
For management regions where multiple MPs meet the conservation objective,
further ranking of the remaining objectives is needed in order to provide decision-makers with a tractable set of trade-off choices.
However this was not undertaken with the first MSE cycle because a fully specified set of objectives has not yet been developed for each management area.

Effective harvest rates for the past 10 years average ~12% (Figure \@ref(fig:harvest-rate)), during which the stock showed no sign of growth, and is estimated to fluctuate at or near $0.3\SB_0$ (Figure \@ref(fig:storyboard-prd)d).
Furthermore, adjacent SARs (HG and CC) show evidence of recent prolonged periods of low biomass and low productivity:
states that were entered rapidly and were preceded by high biomass levels [@kronlund2017].

In the absence of fishing, spawning biomass in `r assess_yr + 1` is forecast to decrease slightly from `r f(prd_final_yr_sbt[2])`&nbsp;t in `r assess_yr` to an estimated `r f(prd_proj_sbt[2])`&nbsp;t (posterior medians).
The forecast spawning biomass in `r assess_yr + 1` is estimated to be below the LRP of $0.3\SB_0$ with `r f(prd_prob_proj_less_03sbo * 100, 1)`% probability in the absence of fishing (Table \@ref(tab:ref-points-prd)).

Harvest options for `r assess_yr + 1` are presented in Table \@ref(tab:decision-table-prd).
These options reflect application of MPs to the `r assess_yr + 1` forecast biomass for PRD,
whereby each MP meets the conservation objective with a minimum 75% probability under the Reference OM (DDM) scenario.
Harvest options under the two Robustness OM scenarios are also included.
For ease of comparison with MSE results [@dfo2019c], all MPs and scenarios listed in Table \@ref(tab:decision-table-prd) include MP performance against the four core objectives.

### Central Coast

For the CC, MPs performing best against the conservation objective have a 10% or lower harvest rate and include a range of operational control point choices.
Similar to PRD, the simulation results for CC indicate there are multiple MPs that meet the conservation objective of maintaining spawning biomass above the LRP with high probability (at least 75%)^\ref{fn:HighProb}^.
For management regions where multiple MPs meet the conservation objective, further ranking of the remaining objectives is needed in order to provide decision-makers with a tractable set of trade-off choices.
However this was not undertaken with the first MSE cycle because a fully specified set of objectives has not yet been developed for each management area.

In the absence of fishing, spawning biomass in `r assess_yr + 1` is forecast at `r f(cc_proj_sbt[2])`&nbsp;t (posterior median), decreasing from `r f(cc_final_yr_sbt[2])`&nbsp;t in `r assess_yr` (Table \@ref(tab:ref-points-cc)).
The `r assess_yr + 1` spawning biomass is forecast to be below the LRP of $0.3\SB_0$ with `r f(cc_prob_proj_less_03sbo * 100, 1)`% probability in the absence of fishing.

Harvest options for `r assess_yr + 1` are presented in Table \@ref(tab:decision-table-cc).
These options reflect application of MPs to the `r assess_yr + 1` forecast biomass for CC,
whereby each MP meets the conservation objective with a minimum 75% probability under the Reference OM (DDM) scenario.
Harvest options under the two Robustness OM scenarios are also included.
For ease of comparison with MSE results [@dfo2019c], all MPs and scenarios listed in Table \@ref(tab:decision-table-cc) include MP performance against the four core objectives.

Additionally, DFO acknowledges commitment to the Heiltsuk Nation for the development of a Joint Fisheries Management Plan for Pacific Herring in the Central Coast in `r assess_yr + 1`.
Results presented here may inform this on-going commitment.

### Strait of Georgia

Closed-loop feedback simulations for the SoG showed that all tested MPs could maintain the spawning biomass above the LRP with 91% probability or higher across all OM scenarios,
including the historical fixed cutoff MP which applied a constant escapement of 21,200&nbsp;t based on the 1996 stock assessment and `r target_hr*100`% harvest rate [@dfo2019a].
Management procedures that included a 30,000&nbsp;t catch cap were able to maintain spawning biomass above a biomass level of $0.6\SB_0$ with 60% probability or higher across all OM scenarios.

A 30,000&nbsp;t catch cap was evaluated for the SoG;
this cap was not often triggered, and thus did not limit the commercial fishery very often in simulations.
The purpose of the catch cap is to provide a model-free means of mitigating the effects of large positive assessment errors on a year-to-year basis.
Additional simulation-evaluations were conducted in 2019 to further explore the role of catch caps in mitigating assessment errors [@dfo2019c].
A comparison of catch caps from 30,000&nbsp;t to 5,000&nbsp;t showed no discernible gain in conservation performance under all 3 OM scenarios.
Results also showed MPs with catch caps of 20,000&nbsp;t or less rarely exceed the 20% harvest rate for any given projection year (over the 15 year projections).

Science advice in 2018 recommended discontinuing the use of the historical fixed cutoff HCR and adopting a HCR with two OCPs for these reasons [@dfo2019a]:

1. The fixed cutoff values were calculated outside of the current assessment model, last updated in 1996,
and therefore ignore 22 years of stock and fishery monitoring data,
as well as substantial changes to the structural form of the assessment model.

1. Use of separate lower and upper OCPs allows for altering the slope of the ramp portion of the HCR to better meet stock and fishery objectives by
avoiding fishery closures and encouraging stock growth as more is learned about stock dynamics and the effects of fishing.

In the absence of fishing, spawning biomass in 2020 is forecast at `r f(sog_proj_sbt[2])`&nbsp;t (posterior median) and is forecast to be below the LRP of $0.3\SB_0$ with `r f(sog_prob_proj_less_03sbo * 100, 1)`% probability in the absence of fishing.

Harvest recommendations for SoG stock in 2018/19 were provided by application of a MP that utilizes stock assessment estimates of
forecast spawning biomass and 
operational control points at $0.3\SB_0$ and $0.6\SB_0$,
with a 20% target harvest rate and
a maximum catch cap of 30,000&nbsp;t [@dfo2019a, Figure 4].

Harvest options for `r assess_yr + 1` are presented in Table \@ref(tab:decision-table-sog).
These options reflect application of MPs to the `r assess_yr + 1` forecast biomass for SoG,
whereby each MP meets the conservation objective with a minimum 75% probability under the Reference OM (DDM) scenario.
Harvest options under the two Robustness OM scenarios are also included.
For ease of comparison with MSE results [@dfo2019c], all MPs and scenarios listed in Table \@ref(tab:decision-table-sog) include MP performance against the four core objectives.

### West Coast of Vancouver Island

For the WCVI, simulation results showed that no tested MP could meet the conservation objective of maintaining spawning biomass above the LRP with high probability
(at least 75%)^\ref{fn:HighProb}^ across the three future natural mortality ($M$) scenarios [@dfo2019a].
In addition, for the scenario where $M$ is most similar to the last 10 years (DIM), the historical fixed cutoff HCR only meet the conservation objective 56% of the time.

Of the MPs that were simulation-tested across the three $M$ scenarios, the "best-performing" MP maintained spawning biomass above the LRP with a 74% probability.
This MP implements a lower control point at the assessment model estimate of $0.5\SB_0$,
a 10% target harvest rate, and
a maximum catch cap of 2,000&nbsp;t.

In the absence of fishing, spawning biomass in 2020 is forecast at `r f(wcvi_proj_sbt[2])`&nbsp;t (posterior median)
and is forecast to be below the LRP of $0.3\SB_0$ with `r f(wcvi_prob_proj_less_03sbo * 100, 1)`% probability in the absence of fishing.

Given the best performing MP for the WCVI did not meet the minimum "high" probability of 75%,
further simulation-testing of HCRs that include additional measures to ensure persistent stock growth away from the critical zone and towards identified biomass targets may be required.
Updates to the operating model (addition of 2018 and 2019 data) and evaluation of additional MPs and objectives (including new objectives) is scheduled to occur in 2020/2021.

As such, the harvest recommendation for the WCVI stock in 2020 is 0&nbsp;t.
