# Tables

```{r data-input}
cap <- paste0("Input data for the ", assess_yr," Pacifc Herring stock assessment. The spawn index has two distinct periods defned by the dominant survey method: surface surveys (", major_start_yr, " to ", new_surv_yr - 1, "), and dive surveys (", new_surv_yr, " to ", major_end_yr, "). The 'spawn index' represents the raw survey data only, and is not scaled by the spawn survey scaling parameter, q.")

input_data_table(inp_catch, cap = cap, french)
```

```{r annual-catch}
cap <- "Total landed catch in tonnes of Pacific Herring in the major stock assessment areas. Legend: Haida Gwaii (HG), Prince Rupert District (PRD), Central Coast (CC), Strait of Georgia (SoG), and West Coast of Vancouver Island (WCVI). Note: 'WP' indicates that data are withheld due to privacy concerns."

total_landed_catch_table(major_catch, by_vec = major_regions_short, cap = cap, french)
```

```{r annual-spawn-on-kelp}
cap <- "Total spawn-on-kelp harvest in pounds of Pacifc Herring in the major stock assessment areas. Legend: Haida Gwaii (HG), Prince Rupert District (PRD), Central Coast (CC), Strait of Georgia (SoG), and West Coast of Vancouver Island (WCVI). Note: 'WP' indicates that data are withheld due to privacy concerns."

sok_harvest_table(sok, by_vec = major_regions_short, first_yr = assess_yr - 10, cap = cap, french)
```

```{r spawn-index-hg}
cap <- "Spawn index in tonnes (t), and proportion of the spawn index by Section within Statistical Area 02 for Pacifc Herring in the Haida Gwaii major stock assessment region. The spawn index is the annual total for the earliest year indicated in the 'Year(s)' column. Proportions indicate the proportion by year, or mean proportion over years, where year(s) are specifed in the ‘Year(s)’ column. The 'spawn index' represents the raw survey data only, and is not scaled by the spawn survey scaling parameter, q."

spawn_index_by_area_table(ps[[en2fr("HG", french)]], cap = cap, french)
```

```{r spawn-index-prd}
cap <- "Spawn index in tonnes (t), and proportion of the spawn index by Statistical Area for Pacifc Herring in the Central Coast major stock assessment region. See Table \\\\@ref(tab:spawn-index-hg) for description."

spawn_index_by_area_table(ps[[en2fr("PRD", french)]], cap = cap, french)
```

```{r spawn-index-cc}
cap <- "Spawn index in tonnes (t), and proportion of the spawn index by Statistical Area for Pacifc Herring in the Central Coast major stock assessment region. See Table \\\\@ref(tab:spawn-index-hg) for description."

spawn_index_by_area_table(ps[[en2fr("CC", french)]], cap = cap, french)
```

```{r spawn-index-sog}
cap <- "Spawn index in tonnes (t), and proportion of the spawn index by Group for Pacifc Herring in the Strait of Georgia major stock assessment region. Legend: '14\\&17' is Statistical Areas 14 and 17 (excluding Section 173); 'ESoG' is eastern Strait of Georgia; 'Lazo' is above Cape Lazo; and 'SDodd' is South of Dodd Narrows. See Table \\\\@ref(tab:spawn-index-hg) for description."

spawn_index_by_area_table(ps[[en2fr("SoG", french)]], cap = cap, french)
```

```{r spawn-index-wcvi}
cap <- "Spawn index in tonnes (t), and proportion of the spawn index by Statistical Area for Pacifc Herring in the West Coast of Vancouver Island major stock assessment region. See Table \\\\@ref(tab:spawn-index-hg) for description."

spawn_index_by_area_table(ps[[en2fr("WCVI", french)]], cap = cap, french)
```

```{r ref-points-hg, results = 'asis', echo = FALSE}
cap <- paste0("Posterior (5\\textsuperscript{th} percentile, Median, and ",
              "95\\textsuperscript{th} percentile) estimates of proposed reference ",
              "points for the Haida Gwaii model. $\\mli{SB}_{2019}$ represents prefishery spawning biomass, ",
              "and all biomass numbers are in thousands of tonnes. Probability of ",
              "$\\mli{SB}_{2019} < 0.3\\mli{SB}_0$ is based on zero catch.")
model_ind <- match(en2fr("HG", french), major_regions_short)
make.ref.points.table(major_models[[model_ind]],
                      xcaption = cap,
                      xlabel = "tab:ref-points-hg",
                      font.size = 11,
                      space.size = 12,
                      placement = "H",
                      translate = french)
```

```{r ref-points-prd, results = 'asis', echo = FALSE}
cap <- paste0("Posterior (5\\textsuperscript{th} percentile, Median, and ",
              "95\\textsuperscript{th} percentile) estimates of proposed reference ",
              "points for the Prince Rupert District model. See Table \\\\@ref(tab:ref-points-hg) for description.")
model_ind <- match(en2fr("PRD", french), major_regions_short)
make.ref.points.table(major_models[[model_ind]],
                      xcaption = cap,
                      xlabel = "tab:ref-points-prd",
                      font.size = 11,
                      space.size = 12,
                      placement = "H",
                      translate = french)
```

```{r ref-points-cc, results = 'asis', echo = FALSE}
cap <- paste0("Posterior (5\\textsuperscript{th} percentile, Median, and ",
              "95\\textsuperscript{th} percentile) estimates of proposed reference ",
              "points for the Central Coast model. See Table \\\\@ref(tab:ref-points-hg) for description.")
model_ind <- match(en2fr("CC", french), major_regions_short)
make.ref.points.table(major_models[[model_ind]],
                      xcaption = cap,
                      xlabel = "tab:ref-points-cc",
                      font.size = 11,
                      space.size = 12,
                      placement = "H",
                      translate = french)
```

```{r ref-points-sog, results = 'asis', echo = FALSE}
cap <- paste0("Posterior (5\\textsuperscript{th} percentile, Median, and ",
              "95\\textsuperscript{th} percentile) estimates of proposed reference ",
              "points for the Strait of Georgia model. See Table \\\\@ref(tab:ref-points-hg) for description.")
model_ind <- match(en2fr("SoG", french), major_regions_short)
make.ref.points.table(major_models[[model_ind]],
                      xcaption = cap,
                      xlabel = "tab:ref-points-sog",
                      font.size = 11,
                      space.size = 12,
                      placement = "H",
                      translate = french)
```

```{r ref-points-wcvi, results = 'asis', echo = FALSE}
cap <- paste0("Posterior (5\\textsuperscript{th} percentile, Median, and ",
              "95\\textsuperscript{th} percentile) estimates of proposed reference ",
              "points for the West Coast Vancouver Island model. See Table \\\\@ref(tab:ref-points-hg) for description.")
model_ind <- match(en2fr("WCVI", french), major_regions_short)
make.ref.points.table(major_models[[model_ind]],
                      xcaption = cap,
                      xlabel = "tab:ref-points-wcvi",
                      font.size = 11,
                      space.size = 12,
                      placement = "H",
                      translate = french)
```

```{r decision-table-hg, results = 'asis', echo = FALSE}
# cap <- "Probabilistic decision table for the Haida Gwaii AM2 model."
# 
# model_ind <- match(en2fr("HG", french), major_regions_short)
# make.decision.table(major_models[[model_ind]],
#                     xcaption = cap,
#                     xlabel = "tab:decision-table-hg",
#                     font.size = 11,
#                     space.size = 12,
#                     placement = "H")
# 
```

```{r decision-table-prd, results = 'asis', echo = FALSE}
cap <- "Probabilistic decision table for the Prince Rupert District AM2 model."

model_ind <- match(en2fr("PRD", french), major_regions_short)
make.decision.table(major_models[[model_ind]],
                    xcaption = cap,
                    xlabel = "tab:decision-table-prd",
                    font.size = 11,
                    space.size = 12,
                    placement = "H")

```

```{r decision-table-cc, results = 'asis', echo = FALSE}
cap <- "Probabilistic decision table for the Central Coast AM2 model."

model_ind <- match(en2fr("CC", french), major_regions_short)
make.decision.table(major_models[[model_ind]],
                    xcaption = cap,
                    xlabel = "tab:decision-table-cc",
                    font.size = 11,
                    space.size = 12,
                    placement = "H")

```

```{r decision-table-sog, results = 'asis', echo = FALSE}
# cap <- "Probabilistic decision table for the Strait of Georgia AM2 model."
# 
# model_ind <- match(en2fr("SoG", french), major_regions_short)
# make.decision.table(major_models[[model_ind]],
#                     xcaption = cap,
#                     xlabel = "tab:decision-table-sog",
#                     font.size = 11,
#                     space.size = 12,
#                     placement = "H")
# 
```

```{r decision-table-wcvi, results = 'asis', echo = FALSE}
# cap <- "Probabilistic decision table for the West Coast Vancouver Island AM2 model."
# 
# model_ind <- match(en2fr("WCVI", french), major_regions_short)
# make.decision.table(major_models[[model_ind]],
#                     xcaption = cap,
#                     xlabel = "tab:decision-table-wcvi",
#                     font.size = 11,
#                     space.size = 12,
#                     placement = "H")
# 
```

