\clearpage

# Appendix {#appendix-minor}

We do not conduct formal analyses of stock trend information for the `r number_to_word(length(minor_regions_short))` Pacific Herring minor SARs (`r commify(minor_regions_full_parens)`).
<!-- However, we do provide time series of landed commercial catch (\autoref{figCatchMinor}), biological data including weight-at-age (\autoref{figWeightAgeMinor}) and proportion-at-age (\autoref{figPropAgeMinor}), as well as the spawn index (\autoref{figSpawnIndexMinor}) from \Sexpr{firstYrMinor} to \Sexpr{max(yrRange)}. -->

```{r app-minor-catch, fig.cap = "Time series of total landed catch in thousands of tonnes of Pacifc Herring from 1977 to 2020 in the minor stock assessment regions. Legend: 'Other' represents the reduction, the food and bait, as well as the special use fishery; 'RoeGN' represents the roe gillnet fshery; and 'RoeSN' represents the roe seine fishery."}
plot_catch(minor_catch,
           xlim = c(1977, 2020),
           translate = french)
```

```{r app-minor-weight-at-age, fig.cap = paste0("Time series of weight-at-age in kilograms (kg) for age-3 (circles) and 5-year running mean weight-at-age (lines) for Pacifc Herring from 1978 to 2018 in the minor stock assessment regions. Lines show 5-year running means for age-2 to age-10 herring (incrementing higher from the lowest line); the thick black line highlights age-3 herring. Missing weight-at-age values (i.e., years where there are no biological samples) are imputed using one of two methods: missing values at the beginning of the time series are imputed by extending the frst non-missing value backwards; other missing values are imputed as the mean of the previous 5 years. Biological summaries only include samples collected using seine nets (commercial and test) due to size-selectivity of other gear types such as gillnet. The age-10 class is a 'plus group' which includes fsh ages 10 and older. Note that vertical axes are cropped at ", wa_ylim[1], " and ", wa_ylim[2], " kg.")}
plot_wa(minor_wa,
        circle_age = 3,
        xlim = c(1974, 2020),
        ylim = wa_ylim,
        translate = french)
```


```{r app-minor-proportions-at-age, fig.cap = paste0("Time series of proportion-at-age for Pacifc Herring from 1978 to 2018 in the minor stock assessment regions. The black line is the mean age, and the shaded area is the approximate 90\\% distribution. Biological summaries only include samples collected using seine nets (commercial and test) due to size-selectivity of other gear types such as gillnet. The age-10 class is a 'plus group' which includes fish ages ", age_plus, "  and older.")}
plot_pa(minor_pa,
        age_plus = age_plus,
        conf = ci_level,
        xlim = c(1978, 2020),
        ylim = c(1, age_plus),
        translate = french)

```

```{r app-minor-survey-indices, fig.cap = "Time series of spawn index in thousands of tonnes for Pacifc Herring from 1978 to 2018 in the minor stock assessment regions. The spawn index has two distinct periods defned by the dominant survey method: surface surveys (1951 to 1987), and dive surveys (1988 to 2018). The dashed vertical line is the boundary between these two periods. The 'spawn index' represents the raw survey data only, and is not scaled by the spawn survey scaling parameter, q."}
plot_spawn_ind(minor_surv,
               xlim = c(1978, 2020),
               ylim = c(0, 15),
               new_surv_yr = new_surv_yr,
               translate = french)
```
\clearpage