# Model description

The Pacific Herring stock assessment is conducted using the integrated statistical catch age model [iSCAM; @martell2011]. 
iSCAM is implemented in a Bayesian estimation framework and is written in AD Model Builder (ADMB, [@admb]).
The original source code and documentation for iSCAM and ADMB are available online. 

This section contains the documentation in mathematical form of the underlying iSCAM
age-structured model, its steady state version that is used to calculate reference points, the
observation models used in predicting observations, and the components of the objective
function that formulate the statistical criterion used to estimate model parameters.
This section will not be included in the final document.

A documented list of symbols used in model equations is given in Table \@ref(tab:variables). 
The documentation presented here is a revised version of the iSCAM user guide available online. 
Much of the text and many of the equations have been taken directly from the original iSCAM user guide.
Note that all the model equations are presented for a sex structured model with $S$ sexes.
Models can therefore be constructed with data for females only, for males and females, or with unsexed data.

This section describes all features of iSCAM, some of which however are not implemented for the Pacific Herring stock assessment.
Note that we refer to iSCAM as a statistical catch-age (SCA) model in the main text.
The following list describes modifications specific to the assessment of Pacific Herring:
  
1. Data are unsexed, $S = 1$,

2. Total mortality is constant across ages, $Z_{t,a} = Z_t$,

3. Fecundity and maturity are synonymous and used interchangeably,

4. Total mortality (i.e., 100% of $Z_t$) occurs prior to spawning, and

5. Unfished spawning biomass is represented as $B_0$ in this section, and as $\mli{SB}_0$ in
the main text.

## Equilibrium considerations: steady-state age structured model

Pacific Herring steady-state age-structured model assuming
unequal vulnerability-at-age,
age-specific fecundity, and
Beverton-Holt recruitment [@beverton1957]. 
Under steady state conditions the parameter vector 
$\Theta$ is assumed to be unknown and can be estimated by fitting the SCA model to 
data, with some restrictions:
  
\begin{equation}\label{eq:Theta-steady}
\Theta = \left(R_0,\,h,\,M\right);\quad
R_0 > 0,\,\,
0.2 \leq h < 1.0,\,\,
M > 0.
\end{equation}

For a given set of growth and maturity-at-age parameters $\Phi$
growth is assumed to follow the Von-Bertalanffy growth model, which describes
the observed length-at-age $l_{a,s}$.
The mean weight-at-age $w_{a,s}$ is given by an allometric relationship,
and age-specific vulnerability $v_a$ is given by an age-based logistic function.

\begin{equation}\label{eq:Phi}
\Phi = \left(l_{\infty,s},\,\acute{k}_s,\,t_{0,s},\,\acute{a}_s,\,
  \acute{b}_s,\,\dot{a}_s,\,\dot{\gamma}_s,\,\hat{a}_k,\,\hat{\gamma}_k\right)
\end{equation}

\begin{equation}\label{eq:l-as}
l_{a,s} = l\left(1-e^{\left(-k_s\left(a-t_{0,s}\right)\right)}\right)
\end{equation}

\begin{equation}\label{eq:w-as}
w_{a,s} = \acute{a}_s\left(l_{a,s}\right)^{\acute{b}_s}
\end{equation}

\begin{equation}\label{eq:v-a}
v_a = \left(1+e^{\left(\frac{-\left(\hat{a}-a\right)}{\hat{\gamma}}\right)}\right)^{-1}
\end{equation}

The terms vulnerability and selectivity are used interchangeably throughout this document, although technically,
selectivity refers to the fishing gear, while
vulnerability refers to all processes affecting the availability of fish to the fishery.
Selectivity parameters can be fixed or estimated.
Fecundity-at-age $f_{a,s}$ is defined in terms of weight-at-age and an age-based logistic function: 
  
\begin{equation}\label{eq:f-as}
f_{a,s}=w_{a,s}\left(1+e^{\left(\frac{-\left(\dot{a}_s-a_s\right)}
                                 {\dot{\gamma}_s}\right)}\right)^{-1}
\end{equation}

Survivorship for unfished and fished populations is 
defined by Equations \@ref(eq:iota-a-1) and \@ref(eq:iota-a-2), 
respectively and it is assumed that all individuals ages $A$ and 
older (i.e., the plus group) have the same total mortality rate.

\begin{equation}\label{eq:iota-a-1}
\iota_a = \begin{cases}
\frac{1}{S}, & a=\acute{a}\\
\iota_{a-1}e^{-M}, & \acute{a}<a<A\\
\frac{\iota_{a-1}}{\left(1-e^{-M}\right)}, & a=A\\
\end{cases}
\end{equation}

\begin{equation}\label{eq:iota-a-2}
\iota_a = \begin{cases}
\frac{1}{S}, & a=\acute{a}\\
\hat{\iota}_{a-1,s}e^{-M-F_ev_{a-1,s}}, & \acute{a}<a<A\\
\frac{\hat{\iota}_{a-1,s}e^{-M-F_ev_{a-1,s}}}{1-e^{-M-F_e v_{a,s}}}, & a=A\\
\end{cases}
\end{equation}

The incidence functions refer to the life-time or per-recruit quantities such as spawning biomass per recruit (Equation \ref{eq:phi-E}) or vulnerable biomass per recruit (Equation \ref{eq:phi-B}).
Note that upper and lower case subscripts denote unfished and fished conditions, respectively.

\begin{equation}\label{eq:phi-E}
\phi_E = \sum_{s=1}^S\sum_{a=\acute{a}}^A \iota_a f_{a,s}
\end{equation}

\begin{equation}\label{eq:phi-e}
\phi_e = \sum_{s=1}^S\sum_{a=\acute{a}}^A \hat{\iota}_{a,s} f_{a,s}
\end{equation}

\begin{equation}\label{eq:phi-B}
\phi_B = \sum_{s=1}^S\sum_{a=\acute{a}}^A \iota_a w_{a,s} v_{a,s}
\end{equation}

\begin{equation}\label{eq:phi-b}
\phi_b = \sum_{s=1}^S\sum_{a=\acute{a}}^A \hat{\iota}_{a,s} w_{a,s} v_{a,s}
\end{equation}

\begin{equation}\label{eq:phi-q}
\phi_q = \sum_{s=1}^S\sum_{a=\acute{a}}^A
\frac{\hat{\iota}_{a,s} w_{a,s} v_{a,s}}{M+F_ev_{a,s}}
\left(1-e^{\left(-M-F_ev_{a,s}\right)}\right)
\end{equation}

Unfished spawning biomass $B_0$ and the recruitment 
compensation ratio $\kappa$ [@myers1999] are estimated by:
  
  \begin{equation}\label{eq:B-0}
B_0 = R_0\phi_B
\end{equation}

\begin{equation}\label{eq:kappa}
\kappa=\frac{4h}{1-h}
\end{equation}

Recruitment is assumed to follow a Beverton-Holt 
stock recruitment relationship,
where the maximum juvenile survival rate $\alpha$ 
and the density-dependent term $\beta$ are given by:
  
\begin{equation}\label{eq:alpha}
\alpha = \frac{\kappa}{\phi_E}  
\end{equation}

\begin{equation}\label{eq:beta}
\beta=\frac{\kappa-1}{R_0\phi_E}
\end{equation}

These equations can then be simplified to the
steady-state equilibrium recruitment $R_e$ needed to calculate 
the equilibrium yield $C_e$ for a given fishing mortality rate $F_e$:
  <!-- SH - write something about phi_q? -->
  
  \begin{equation}\label{eq:R-e}
R_e = R_0 \frac{\kappa-\frac{\phi_E}{\phi_e}}{\kappa-1}  
\end{equation}

\begin{equation}\label{eq:C-e}
C_e = F_e R_e \phi_q
\end{equation}

These steady-state conditions are critical for 
determining various reference points such as
$F_\text{MSY}$ and $B_\text{MSY}$. iSCAM calculates 
$F_\text{MSY}$ by finding the value of 
$F_e$ that results in the zero derivative of Equation \@ref(eq:C-e).
This is accomplished numerically using a Newton-Raphson method 
where an initial guess for
$F_\text{MSY}$ is set equal to $M$. 
Given an estimate of $F_\text{MSY}$, other reference points such as $MSY$ and
$B_\text{MSY}$ can be calculated. However, these reference points 
are not currently used in the Pacific Herring assessment.

## Dynamic state: statistical catch-age model

The estimated parameter vector in the 
dynamic state version of iSCAM is defined by $\Theta$,
where $R_0$, $h$, and $M$, are the leading population 
parameters that define the overall scale and 
productivity of the population. 

\begin{equation}\label{eq:Theta-catch}
\Theta = \left(R_0,\,h,\,M,\,\overline{R},\,\overline{R}_{\mli{init}},\,\vartheta^2,\,\rho,\,
               \Gamma_{k,t},\,\{\omega_t\}_{\acute{t}=1-A}^{\acute{t}=T},\,
               \{\omega_{\mli{init},t}\}_{t=\acute{t}-A}^{t=\acute{t}-1}\right)
\end{equation}

The variance components of the model are partitioned using an errors in variables approach. 
The key variance parameter is the inverse of the total variance $\vartheta^2$ (i.e., total precision).
This parameter can be fixed or estimated, and was fixed for this model.
The total variance is partitioned into observation $\sigma$ and process error $\tau$ components by the model parameter $\rho$,
which represents the proportion of the total variance that is due to observation error [@punt1999; @deriso2007].

\begin{equation}\label{eq:sigma}
\sigma = \sqrt{\rho}\vartheta
\end{equation}

\begin{equation}\label{eq:tau}
\tau = \sqrt{\left(1-\rho\right)}\vartheta  
\end{equation}

The unobserved state variables (Equation \ref{eq:N-tas-unobs})
include the numbers-at-age each year $N_{t,a,s}$,
the spawning stock biomass $B_{t,s}$, 
and the total age-specific total mortality rate $Z_{t,a,s}$.

\begin{equation}\label{eq:N-tas-unobs}
N_{t,a,s},\,\, B_{t,s},\,\, Z_{t,a,s}
\end{equation}

Initial numbers-at-age in the first year (Equation \ref{eq:N-tas-init-1}) and
the annual recruits (Equation \ref{eq:N-tas-init-2})
are treated as estimated parameters and used to initialize the numbers-at-age array.
\begin{equation}\label{eq:N-tas-init-1}
N_{t,a,s} = \frac{1}{S}\overline{R}_\mli{init}e^{\omega_{\mli{init},t}}e^{-M\left(a-1\right)};\quad
\left(\acute{t}-A\right) < t < 1,\,\,
\acute{a} \leq a \leq A
\end{equation}

\begin{equation}\label{eq:N-tas-init-2}
N_{t,a,s} = \frac{1}{S}\bar{R}e^{\omega_{t}};\quad
\acute{t} \leq t \leq T;\,\,
a = \acute{a}.  
\end{equation}

Vulnerability-at-age $v_{k,a}$ is assumed to be time-invariant and is modelled using a two-parameter logistic function (Equation \ref{eq:v-ka}).
The annual fishing mortality for each gear $k$ in year $t$ is the exponent of the estimated vector $\Gamma_{k,t}$ (Equation \ref{eq:F-kt}).
The vector of log fishing mortality rate parameters $\Gamma_{k,t}$ is a bounded vector with a 
minimum value of $-30.0$ and a maximum value of $3.0$.
In arithmetic space this corresponds to a
minimum value of $9.36^{-14}$ and a maximum value of $20.01$ for annual fishing mortality rates.
In years where there are zero reported catches for a given fleet,
no corresponding fishing mortality rate parameter is estimated and the implicit assumption is there was no fishery in that year.

\begin{equation}\label{eq:v-ka}
v_{k,a} = \frac{1}{1+e^{-\frac{\left(a - \hat{a}_k\right)}{\hat{\gamma}_k}}}  
\end{equation}

\begin{equation}\label{eq:F-kt}
F_{k,t} = e^{\Gamma_{k,t}}
\end{equation}

State variables in each year are updated using 
Equations \@ref(eq:B-ts-state) to \@ref(eq:N-tas-state),
where the spawning biomass is the product of the 
numbers-at-age and the mature biomass-at-age 
(Equation \ref{eq:B-ts-state}). The total mortality rate 
is given by Equation \@ref(eq:Z-tas-state), and the total 
catch (in weight) for each gear is given by Equation \@ref(eq:C-kt), 
assuming that both natural and fishing mortality 
occur simultaneously throughout the year. The sex-specifc 
numbers-at-age are propagated over time using 
(Equation \ref{eq:N-tas-state}), where members of the plus group
(age A) are all assumed to have the same total mortality 
rate $Z_{t,a,s}$. 

\begin{equation}\label{eq:B-ts-state}
\mli{B}_{t,s} = \sum_{a=\acute{a}}^A N_{t,a,s}f_{a,s}
\end{equation}

\begin{equation}\label{eq:Z-tas-state}
Z_{t,a,s} = M+\sum_{k=1}^K F_{k,t} v_{k,t,a,s}
\end{equation}

\begin{equation}\label{eq:C-kt}
\hat{C}_{k,t} = \sum_{s=1}^S \sum_{a=\acute{a}}^A \frac {N_{t,a,s}w_{a,s}F_{k,t}
v_{k,t,a,s} \left( 1-{e^{-Z_{t,a,s}}} \right) }{Z_{t,a,s}}^{\eta_t}
\end{equation}

\begin{equation}\label{eq:N-tas-state}
N_{t,a,s} = \begin{cases}
\frac{\alpha E_{t-1}}{1+\beta E_{t-1}} e^{\left(\omega_t-0.5\tau^2\right)}, & a=\acute{a}\\
N_{t-1,a-1,s} e^{\left(-Z_{t-1,a-1,s}\right)}, & \acute{a}<a<A\\
N_{t-1,a,s} e^{\left(-Z_{t-1,a,s}\right)}, & a=A\\
\end{cases}
\end{equation}

Recruitment to age k (where k in this case refers to the 
start age, which for Pacific Herring is age 2) is assumed 
to follow a Beverton-Holt model for Pacific Herring 
(Equation \ref{eq:R-t}) where the maximum juvenile survival 
rate $\alpha$ is defined by Equation \@ref(eq:alpha) and 
$\beta$ is derived from Equation \@ref(eq:beta),
which is conditional on estimates of $h$ and $R_0$.

\begin{equation}\label{eq:R-t}
R_t = \frac{\alpha B_{t-k}}{1+\beta B_{t-k}}e^{\delta_{t}-0.5\tau^2}
\end{equation}

### Residuals, likelihoods, and objective function value components

The objective function contains five major components:

1. The negative log-likelihood for the catch data,

2. The negative log-likelihood for the relative abundance data,

3. The negative log-likelihood for the age composition data,

4. The prior distributions for model parameters, and

5. Three penalty functions that are invoked to regularize the solution during intermediate
phases of the non-linear parameter estimation. 

The penalty functions:

a. Constrain the estimates of annual recruitment to conform to a Beverton-Holt stock-recruit
function,

b. Weakly constrain the log recruitment deviations to a normal distribution, and

c. Weakly constrain estimates of log fishing mortality to a normal distribution
($\sim$ $N$(ln(0:2); 4:0)) to prevent estimates of catch from exceeding estimated biomass.

Sensitivity analysis indicate that the model is insensitive 
to changes in the penalty function parameters, indicating that
the other likelihood components and prior probability distributions 
were the most important contributors to the objective function.

The objective function components are discussed in more detail in the following sections.

### Observed catch

It is assumed that the measurement errors in the catch observations
are log-normally distributed, and the residuals given by:


\begin{equation}\label{eq:ets_kt}
\eta_{k,t} = \text{ln}\left(C_{k,t} + o) - ln(\hat{C}_{k,t} + o\right)
\end{equation}

where $o$ is a small constant ($e^{-10}$) to ensure the residual is 
defined in the case of a zero catch observation. The residuals 
are assumed to be normally distributed with a user-specified standard
deviation $\sigma_C$. At present, it is assumed that observed catches for each 
gear $k$ have the same standard deviation. The negative loglikelihood (ignoring the scaling constant) for the catch data is given by:

\begin{equation}\label{eq:ell_C}
\ell_C = \sum_k\left[T_k \text{ln}\left(\sigma_C\right)+
\frac{\sum_t\left(\eta_{k,t}\right)^2}{2\sigma_C^2}\right] 
\end{equation}

where $T_k$ is the total number of catch observations for gear type $k$.

### Relative abundance 

For Pacific Herring the relative abundance data are 
assumed to be proportional to spawning biomass so the 
$k^\text{th}$ survey the vulnerable biomass available to the survey sampling gear:

\begin{equation}\label{eq:V_kt}
V_{k,t} = \sum_{a}B_{t,a}e^{-\lambda_{k,t}M_{t,a}}f_{a,t} 
\end{equation}

A user specified fraction of the total mortality $\lambda_{k,t}$ 
adjusts the numbers-at-age to correct for survey timing. 
The residuals between the observed and predicted relative abundance index is given by:

\begin{equation}\label{eq:epsilon_kt}
\epsilon_{k,t} = \text{ln}\left(I_{k,t}\right) - \text{ln}\left(q_k\right)+\text{ln}\left(V_{k,t}\right)
\end{equation}

where $I_{k,t}$ is the observed relative abundance index, 
$q_k$ is the catchability coefficient for index $k$, and 
$V_{k,t}$ is the predicted vulnerable biomass at the time 
of sampling. The catchability coefficient $q_k$ is evaluated 
at its conditional maximum likelihood estimate:

\begin{equation}\label{eq:q_kt}
q_k = \frac{1}{N_k}\sum_{t \in I_{k,t}} \text{ln}\left(I_{k,t}\right) - \text{ln}\left(V_{k,t}\right)
\end{equation}

where $N_k$ is the number of relative abundance observations for index $k$ [see @walters1994 for more information].
The negative loglikelihood for relative abundance data is given by:

\begin{equation}\label{eq:ell_I}
\ell_I = \sum_k \sum_{t \in I_{k,t}} \text{ln}\left(\sigma_{k,t}\right)+\frac{\epsilon_{k,t}^2}{2\sigma_{k,t}^2}
\end{equation}

The standard deviation $\sigma_{k,t}$ is calculated by:

\begin{equation}\label{eq:sigma_kt}
\sigma_{k,t} = \frac{\rho \varphi^2}{ \omega_{k,t}} 
\end{equation}

where $\rho\varphi^2$ is the proportion of the total error that is 
associated with observation errors, and $\omega_{k,t}$ is a user specified 
relative weight for observation $t$ from gear $k$. The $\omega_{k,t}$ 
allow each observation to be weighted relative to the total error 
$\rho\varphi^2$. For example, to omit a particular observation, 
set $\omega_{k,t}$ = 0, or to give 2 times the weight, 
set $\omega_{k,t}$ = 2.0. To assume all observations have the 
same variance then simply set $\omega_{k,t}$ = 1. 
Note that if $\omega_{k,t}$ = 0 then Eq. \ref{eq:ell_I} is undefined; 
therefore, iSCAM adds a small constant ($e^{-10}$) to $\omega_{k,t}$, 
which is equivalent to assuming an extremely large variance) 
to ensure the likelihood can be evaluated.

In the case of the Pacific Herring assessment, 
the spawn survey data post 1988 were assumed to be 1.166 times 
as precise as the pre-dive survey data (1951-1987). 
To implement this, objective function weights for the 1951-1987 
data were set equal to unity and the contemporary
data was assigned a relative weight of 1.166. 
The standard deviation in the observation errors is
conditional on estimated values of $\rho$ and $\varphi^2$.

### Age Composition

Sampling theory suggest that age composition data are 
derived from a multinomial distribution [@fournier1982]. 
However, iSCAM assumes that age-proportions are obtained
from a multivariate logistic distribution [@schnute1995; @richards1997].
iSCAM departs from the traditional multinomial model due to 
choices regarding weighting of the age-composition data in the objective function. 
First, the multinomial distribution requires the specification of an effective sample size. 
This weighting may be done arbitrarily or through iterative 
re-weighting [@mcallister1997; @gavaris2002],
and in the case of multiple and potentially conflicting 
age-proportions this procedure may fail to converge properly. 
The assumed effective sample size can have a large impact on the overall model results.

A feature of the multivariate logistic distribution is 
that the age-proportion data can be weighted
based on the conditional maximum likelihood estimate 
of the variance in the age-proportions.
Therefore, the contribution of the age-composition 
data to the overall objective function is
“self-weighting” and is conditional on other components 
in the model. Ignoring the subscript for
gear type for clarity, the observed and predicted 
proportions-at-age must satisfy the
constraint for each year:

\begin{equation}\label{eq:p_ta}
\sum^{A}_{a=1} p_{t,a} = 1 
\end{equation}

The residuals between the observed $p_{t,a}$and 
predicted proportions $\hat{p}_{t,a}$ is given by:

\begin{equation}\label{eq:ets_ta}
\eta_{t,a} = \text{ln}\left(p_{t,a}\right) - \text{ln}\left(\hat{p}_{t,a}\right)-\frac{1}{A}
\sum^{A}_{a=1}\left[\text{ln}\left(p_{t,a}\right) - \text{ln}\left(\hat{p}_{t,a}\right)\right]
\end{equation}

The conditional maximum likelihood estimate of 
the variance is given by:

\begin{equation}\label{eq:hattau}
\hat{\tau}^2=\frac{1}{\left(A-1\right)T}\sum^{T}_{t=1}\sum^{A}_{a=1}\eta_{t,a}^2
\end{equation}

The negative loglikelihood evaluated at the conditional 
maximum likelihood estimate of the variance is given by:

\begin{equation}\label{eq:ell_A}
\ell_A = \left(A-1\right)T \text{ln}\left(\hat{\tau}^2\right)
\end{equation}

In short, the multivariate logistic likelihood for 
age-composition data is the log of the residual 
variance weighted by the number observations 
over years and ages.

### Stock recruitment

The Pacific Herring stock assessment assumes Beverton-Holt recruitment. 
Annual recruitment and the initial age-composition 
are treated as latent variables in iSCAM, 
and residuals between estimated recruits and the deterministic 
stock-recruitment models are used to estimate unfished 
spawning stock biomass and recruitment compensation. 
The residuals between the estimated and predicted recruits is given by:

\begin{equation}\label{eq:delta-t}
\delta_t = \text{ln}\left(\bar{R}e^{\omega_{t}}\right) - R_t
\end{equation}

where $R_{t}$ is given by Eq.\@ref(eq:R-t), 
and $k$ is the age at recruitment. 
Note that a bias correction term for the 
lognormal process errors is included in Eq.\@ref(eq:R-t).
The negative loglikelihood for the recruitment 
deviations is given by the normal density (ignoring the scaling constant):
  
\begin{equation}\label{eq:l-delta}
\ell_{\delta} = nln\left(\tau\right) +\frac{\sum^{T}_{t=1} +k^{\delta_{t}^2}}{2\tau^2}
\end{equation}

Eqs.\@ref(eq:delta-t) and \@ref(eq:l-delta) are key for 
estimating unfished spawning stock biomass and 
recruitment compensation via the recruitment models. 
The relationship between ($\alpha$, $\beta$) and 
($B_0$, $\kappa$) is defined by Eqs.\@ref(eq:alpha) 
and \@ref(eq:beta). Where again $\alpha$ is the maximum juvenile 
survival rate, and $\beta$ is the density effect on recruitment, 
and $B_0$ is the unfished spawning stock biomass. Unfished steady-state 
spawning stock biomass per recruit is given by $\phi_{E}$, Eq.\@ref(eq:phi-E), 
which is the sum of products between age-specific survivorship and
relative fecundity. In the cases where the natural mortality rate 
is allowed to vary over time, the calculation of $\phi_{E}$, 
and the corresponding unfished spawning stock biomass ($B_{0}$) 
is based on the average natural mortality rate over the 
entire time period. This subtle calculation has implications
for reference point calculations in cases where there are 
increasing or decreasing trends in
natural mortality rates trend upwards, estimates of $B_{0}$ decrease.

## Parameter estimation and uncertainty

There are five distinct components that make up the objective function $f$ that is being minimized by the iSCAM model:
\begin{multline}\label{eq:f}
f = \text{negative loglikelihoods} + \text{constraints} +
\text{priors for parameters}\\
+ \text{survey priors} + \text{convergence penalties}.
\end{multline}
  
The purpose of this section is to completely document all of the components that make up the objective function.

#### Negative loglikelihoods 

The negative loglikelihoods pertain specifically to elements that deal
with the data and variance partitioning,
and have already been described in detail in earlier sections.
There are four specific elements that make up the vector of the objective function:

\begin{equation}\label{eq:l-sum}
\vec{\ell} = \left(\ell_C,\,\ell_I,\,\ell_A,\,\ell_\delta\right).
\end{equation}

To reiterate, these are the likelihood of the catch data $\ell_C$, 
likelihood of the survey data $\ell_I$, 
the likelihood of the age-composition data $\ell_A$, 
and the likelihood of the stock-recruitment residuals $\ell_\delta$.
Each of these elements are expressed in negative log-space,
and ADMB attempts to estimate model parameters by minimizing the sum of these elements.

#### Constraints

There are two specific constraints that are described here: 
1) parameter bounds, and 
2) constraints to ensure that a parameter vector sums to 0. 
In iSCAM the user must specify the lower and upper bounds 
for the leading parameters defined in the control file
($ln(R_0)$, $h$, $ln(M)$, $ln(\bar{R})$, $ln(\ddot{R})$, $\rho$, $\vartheta$). 

All estimated selectivity parameters $\gamma_k$ are estimated in log
space and have a minimum and maximum values of -5.0 and 5.0, 
respectively. These values are hard-wired into the code, but should be sufficiently large/small enough to capture a wide range of selectivities. 
Estimated fishing mortality rates are also constrained (in log space) to have a
minimum value of -30, and a maximum value of 3.0, also hard-wired. 

Log annual recruitment deviations are also constrained to have minimum and maximum values of -15.0 and 15.0 and there is an additional constraint to ensure the 
vector of deviations sums to 0. This is necessary in order to be able to estimate the average recruitment $\bar{R}$. Finally, the annual log deviations in natural mortality rates are constrained to lie between -5.0 and 5.0.

#### Parameter priors

Each of the seven leading parameters specified in the control file
($ln(R_0)$, $h$, $ln(M)$, $ln(\bar{R})$, $ln(\ddot{R})$, $\rho$, $\vartheta$)
are declared as bounded parameters and in addition the user 
can also specify an informative prior distribution for each of these parameters. Five distinct prior distributions can be implemented:
uniform $\mathcal{U}$, normal $\mathcal{N}$, lognormal $\mathcal{L}$, beta $\mathcal{B}$, and gamma $\mathcal{G}$.
For Pacific Herring,
a bounded recruitment uniform prior was specified for the log of unfished recruitment $\mathcal{U}(-5, 15)$,
a beta prior was assumed for steepness $\mathcal{B}(10.0, 4.92)$,
a normal prior was specified for the log of natural mortality rate $\mathcal{N}(-0.79, 0.4)$,
a bounded uniform prior for both the log of initial recruitment and average recruitment $\mathcal{U}(-5.0, 15.0)$,
a beta prior for the variance partitioning parameter $\rho \sim \mathcal{B}(17:086; 39:0559)$,
and a gamma prior for the inverse total standard deviation parameter $\vartheta \sim \mathcal{G}(25; 28:75)$.
The scaling parameter $q$ for each of the surveys is not treated 
as an unknown parameter within the code; rather, the maximum posterior 
density estimate for $ln(q)$ conditional on all other parameters is 
used to scale the predicted spawning biomass to the observed acoustic biomass index. 
For the AM2 version of the Pacific Herring assessment model the prior on $q_1$ was assumed uninformative $q_1 \sim \mathcal{N}(0, 1)$, and informative for $q_2 \sim \mathcal{N}(1;0:01)$.

\begin{table}[ht]
\centering
\caption{\label{tab:variables}Description of symbols and constants in the
  Pacific Herring statistical catch-age model.}
\begin{tabular}{lll}
\toprule
\bf{Symbol} & \bf{Value} & \bf{Description}\\
\midrule
\multicolumn{3}{l}{\textbf{Indices}}\\
$s$ & & Index for sex\\
$a$ & & Index for age\\
$t$ & & Index for year\\
$k$ & & Index for gear\\
\multicolumn{3}{l}{\textbf{Model dimensions}}\\
$S$ & $`r major_models[[1]]$dat$num.sex`$ & Number of sexes\\
$\acute{a},\,A$ & $`r major_models[[1]]$dat$start.age`$, $`r major_models[[1]]$dat$end.age`$ & Youngest and oldest age class ($A$ is a plus group)\\
$\acute{t},\,T$ & $`r major_models[[1]]$dat$start.yr`$, $`r major_models[[1]]$dat$end.yr`$ & First and last year of catch data\\
$K$ & $`r major_models[[1]]$dat$num.gears`$ & Number of gears including survey gears\\
\multicolumn{3}{l}{\textbf{Observations (data)}}\\
$C_{k,t}$ & & Catch in weight for gear $k$ in year $t$\\
$I_{k,t}$ & & Relative abundance index for gear $k$ in year $t$\\
\multicolumn{3}{l}{\textbf{Estimated parameters}}\\
$R_0$ & & Age-$\acute{a}$ recruits in unfished conditions\\
$h$ & & Steepness of the stock-recruitment relationship\\
$\bar{R}$ & & Average age-$\acute{a}$ recruitment from year $\acute{t}$ to $T$\\
$\bar{R}_\mli{init}$ & & Average age-$\acute{a}$ recruitment in year $\acute{t}-1$\\
$M_s$ & & Instantaneous natural mortality rate\\
$\hat{a}_k$ & & Selectivity parameter for gear $k$\\
$\hat{\gamma}_k$ & & Selectivity parameter for gear $k$\\
$\Gamma_{k,t}$ & & Logarithm of the instantaneous fishing mortality for gear $k$ in year $t$\\
$\omega_t$ & & Age-$\acute{a}$ deviates from $\bar{R}$ for years $\acute{t}$ to $T$\\
$\omega_{\mli{init},t}$ & & Age-$\acute{a}$ deviates from $\bar{R}_\mli{init}$ in year $\acute{t}$\\
$q_k$ & & Catchability parameter for survey $k$\\
$\rho$ & & Fraction of the total variance associated with observation error\\
$\vartheta^2$ & & Total precision (inverse of variance) of the total error\\
\multicolumn{3}{l}{\textbf{Standard deviations}}\\
$\sigma$ & & Standard deviation for observation errors in survey index\\
$\tau$ & & Standard deviation in process errors (recruitment deviations)\\
$\sigma_{C,k}$ & & Standard deviation in observed catch for gear $k$\\
\multicolumn{3}{l}{\textbf{Residuals}}\\
$\delta_t$ & & Recruitment residual in year $t$\\
$\eta_t$ & & Residual error in predicted catch in year $t$\\
\multicolumn{3}{l}{\textbf{Fixed growth and maturity parameters}}\\
$l_{\infty,s}$ & & Asymptotic length in millimetres for sex $s$\\
$\acute{k}_s$ & & Brody growth coefficient for sex $s$\\
$t_{0,s}$ & & Theoretical age at zero length for sex $s$\\
$\acute{a}_s$ & & Scalar in length-weight allometry for sex $s$\\
$\acute{b}_s$ & & Power parameter in length-weight allometry for sex $s$\\
$\dot{a}_s$ & & Age at 50\% maturity for sex $s$\\
$\dot{\gamma}_s$ & & Standard deviation at 50\% maturity for sex $s$\\
\bottomrule
\end{tabular}
\end{table}