---
title: "Stock status update with application of management procedures for Pacific Herring (*Clupea pallasii*) in British Columbia: Status in 2023 and forecast for 2024"
title_short: "Pacific Herring status in 2023 and forecast for 2024"
title_other: "Mise à jour de l'état des stocks avec application des procédures de gestion pour le hareng du Pacifique (*Clupea pallasii*) en Colombie-Britannique: État en 2023 et prévisions pour 2024"
# title: "Mise à jour de l'état des stocks avec application des procédures de gestion pour le hareng du Pacifique (*Clupea pallasii*) en Colombie-Britannique: État en 2023 et prévisions pour 2024"
# title_short: "État du hareng du Pacifique en 2023 et prévisions pour 2024"
# title_other: "Stock status update with application of management procedures for Pacific Herring (*Clupea pallasii*) in British Columbia: Status in 2023 and forecast for 2024"
work_done_year: 2023
work_done_month: Month
# work_done_month: Mois
report_number: 000
isbn: 978-0-660-00000-0
# isbn: 978-0-660-00000-0
approver: |
  Andrew Thomson\
  Regional Director
# Directeur régionale
approval_year: 2023
approval_month: September
# approval_month: Septembre
approval_day: 00
process_year: 2023
process_month: September
# process_month: Septembre
process_day: 22
branch: Science Branch
region: Pacific Region
# branch: Secteur des sciences
# region: Région du Pacifique
output:
  csasdown:::sr_pdf:
    french: FALSE
    prepub: FALSE
    copy_sty: TRUE
    line_nums: FALSE
    line_nums_mod: 1
    draft_watermark: FALSE
    highlight: tango
type: sr
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: TRUE
bibliography: bib/refs.bib
# bibliography: bib/refs_fr.bib
lot: TRUE
lof: TRUE
header-includes:
  - \usepackage{needspace}
  - \usepackage{afterpage}
---

\sloppy

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)

if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "pdf"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "ragg_png"
}

fig_asp <- 0.618
fig_width <- 6.5
fig_out_width <- "6.5in"
fig_dpi <- 320
fig_align <- "center"
fig_pos <- "ht"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = "H"
)

options(
  xtable.comment = FALSE,
  kableExtra.latex.load_packages = FALSE,
  width = 80,
  scipen = 999
)
```

```{r metadata}
library(rmarkdown)
library(stringr)

meta <- metadata$output

if (is.null(meta)) {
  options(french = FALSE)
} else {
  if (length(grep("pdf", names(meta)))) {
    french <- meta$`csasdown:::sr_pdf`$french
    options(french = french)
    prepub <- meta$`csasdown:::sr_pdf`$prepub
  } else if (length(grep("word", names(meta)))) {
    french <- meta$`csasdown::sr_word`$french
    options(french = french)
    prepub <- meta$`csasdown::sr_word`$prepub
  }
}

csl <- "csl/csas.csl"
if (getOption("french")) {
  csl <- "csl/csas-french.csl"
  options(OutDec = ",")
}

cat_no <- paste0(
  "Fs70-7/",
  metadata$work_done_year,
  "-",
  str_pad(string = metadata$report_number, width = 3, pad = "0"),
  ifelse(french, "F", "E"),
  "PDF"
)
```

```{r load-libraries, cache=FALSE}
library(tidyverse)
library(directlabels)
library(reshape2)
library(kableExtra)
library(here)
library(rosettafish)
library(csasdown)
library(gfutilities)
library(gfiscamutils)
library(ggrepel)
library(herringutils)
library(gcookbook)
library(readr)
library(zoo)

assess_yr <- 2023

models_dir <- here("models")
major_stock_dir <- list("HG", "PRD", "CC", "SoG", "WCVI")
minor_stock_dir <- list("A27", "A2W")
special_stock_dir <- list("A10")

mcmc_length <- 20000000 # Default: 20,000,000
mcmc_samp_freq <- 4000  # Default: 4,000
mcmc_burnin <- 1000     # Default: 1,000
retro_yrs <- 1:10       # Default: 1:10

run_sca_models <- FALSE            # Run SCA for SARs in `major_stock_dir`
rebuild_rdata_model_files <- FALSE # Rebuild RData files (replace existing)
run_retros <- FALSE                # Run retrospectives

source(here("R", "run-sca.R"))
source(here("R", "model-setup.R"))
source(here("R", "variable-setup.R"))
source(here("R", "hcr.R"))

theme_set(herring_theme())
```

```{r output-options}
keep_non_CC <- TRUE     # FALSE to provide preliminary CC report
show_ic_figures <- TRUE # Show/hide incidental catch figures
slides <- FALSE         # Make figures for powerpoint slides
```

<!-- Distributions -->
\newcommand{\dUnif}[2]{$\mathcal{U}\left(#1, #2\right)$}
\newcommand{\dNorm}[2]{$\mathcal{N}\left(#1, #2\right)$}
\newcommand{\dLognorm}[2]{$\emph{Lognormal}\left(#1, #2\right)$}
\newcommand{\dBeta}[2]{$\emph{Beta}\left(#1, #2\right)$}
\newcommand{\dGamma}[2]{$\emph{Gamma}\left(#1, #2\right)$}

<!-- Other math -->
\newcommand{\lognorm}{\text{ln}}
\newcommand{\SB}{\mli{`r en2fr("SB", translate = french)`}}
\newcommand{\AVE}{\text{`r en2fr("AVE", translate = french)`}}

---
csl: `r csl`
cat_no: `r cat_no`
---

<!-- Compile the PDF on the command line: -->
<!-- bookdown::render_book("index.Rmd") -->
