# Renseignements de base

En Colombie-Britannique, le hareng du Pacifique est géré selon `r number_to_word(length(major_regions_short))` régions principales d’évaluation des stocks et
`r number_to_word(length(minor_regions_short))` régions secondaires d’évaluation des stocks 
(SARs; figure \@ref(fig:bc-map)).
Les régions principales d’évaluation des stocks sont `r commify(major_regions_full_parens)`.
Les régions secondaires d’évaluation des stocks sont `r commify(minor_regions_full_parens)`.
Nous effectuons des analyses officielles des informations concernant les tendances des stocks pour les régions principales d’évaluation des stocks.
Dans le cas des régions secondaires d’évaluation des stocks, nous présentons les données sur les 
prises, les données biologiques et les données des relevés de ponte disponibles
(section "\nameref{sec:app-minor}").
Depuis 2021, nous incluons des données similaires pour la zone spéciale, la zone 10
(section "\nameref{sec:app-special}").
Veuillez noter que la zone 10 est un sous-ensemble de la côte centrale
et se trouve hors des limites de la région d’évaluation des stocks.
Aucune analyse officielle des tendances des stocks n’est incluse en ce qui concerne
les régions secondaires d’évaluation des stocks ou les zones spéciales.

## Description de la pêche

À l’heure actuelle, il y a plusieurs pêches du hareng du Pacifique en Colombie-Britannique.
Les Premières Nations ont un accès prioritaire, après que les mesures de conservation ont été appliquées,
à la pêche à des fins alimentaires, sociales et rituelles (ASR).
Les possibilités de pêche commerciale consistent en quatre pêches dirigées:
nourriture et appâts;
usages spéciaux;
œufs sur varech;
hareng rogué.
Il existe également une petite pêche récréative.

Les Premières Nations pêchent le hareng entier, le hareng rogué et
les œufs de hareng à des fins ASR.
Le hareng entier est pêché à la senne, au filet maillant, au râteau, à l’épuisette et à la turlutte.
Les œufs de hareng sont récoltés sous forme de rogue sur des algues marines, comme le varech (œufs sur varech), ou
sous forme de rogue sur des branches d’arbres placées sur les lieux de fraie. 
La pêche autochtone du hareng à des fins alimentaires, sociales et rituelles peut avoir lieu sur toute la côte
lorsqu’elle est autorisée par un permis communautaire.

De plus, la pêche commerciale autochtone et la pêche commerciale en vertu d’un traité peuvent être pratiquées
dans certaines régions d’évaluation spécifiques.
Quatre traités modernes (Nisga'a, Tsawwassen, Maa-nulth et Tla'amin)
ont été ratifiés en Colombie-Britannique et énoncent un droit issu d’un traité à la pêche du poisson à des fins ASR.
Les cinq Premières Nations Nuu-chah-nulth habitant la côte ouest de l’île de Vancouver
(Ahousaht, Ehattesaht, Hesquiaht, Mowachaht/Muchalaht et Tla-o-qui-aht,
les cinq Nations),
jouissent de droits ancestraux de pêcher toute espèce de poisson,
à l’exception de la panope du Pacifique,
dans leurs territoires de pêche et de vendre ce poisson.
Le MPO a élaboré un plan de gestion des pêches (PGP) multi-espèces des cinq Nations pour 2022-2023.
Le PGP comprend des renseignements spécifiques sur la pêche, tels que
les allocations/l’accès,
les permis et les désignations,
la zone de pêche,
les possibilités de récolte, et
la surveillance des pêches et la déclaration des prises.
Le MPO a tenu compte des commentaires fournis par les cinq Nations lors des consultations 
et il les a intégrés dans le PGP pour 2022-2023 dans la mesure du possible.

La mise en œuvre de la pêche destinée à la vente, fondée sur les droits des cinq Nations,
est un processus continu.
Le PGP pour 2022-2023 est le quatrième PGP multi-espèces élaboré dans le but de mettre en œuvre 
la pêche multi-espèces fondée sur le droit pour tenir compte des droits ancestraux 
des cinq Nations, conformément à l’arrêt de 2018 de la Cour suprême de la Colombie-Britannique. 
La version 2 du PGP pour 2021, publiée le 2 décembre 2021,
a été le premier PGP multi-espèces élaboré
suite à l’arrêt de la Cour d’appel de la Colombie-Britannique (BCCA)
du 19 avril 2021 dans l’affaire opposant la Bande et nation indienne Ahousaht et le Canada, 
2021 BCCA 155. Mais ce PGP n’a été mis en œuvre que partiellement.

Le PGP pour 2022-2023 aborde la plupart des questions restantes
soulevées par l’arrêt de la Cour d’appel de la Colombie-Britannique, ce qui laisse quelques points à examiner.
Le MPO a l’intention de continuer à réviser le PGP et d’apporter d’autres changements 
en cours de saison, et de modifier le PGP au besoin. 
Pour obtenir de plus amples renseignements, consultez le PGP pour 2022-2023
\link{https://waves-vagues.dfo-mpo.gc.ca/Library/40953798.pdf}{FMP}.

Sur la côte centrale,
la Première Nation Heiltsuk a le droit ancestral de récolter
les œufs sur varech du hareng du Pacifique à des fins commerciales.
Les Heiltsuk détiennent actuellement neuf permis de pêche des œufs sur varech dans cette région,
et cette pêche est pratiquée en utilisant la méthode préférée des Heiltsuk,
c’est-à-dire en étang ouvert.
Le MPO et les Heiltsuk se sont également engagés à élaborer chaque année
un plan conjoint de gestion des pêches en ce qui concerne le hareng du Pacifique sur la côte centrale.

En `r this_season`, les principales pêches de hareng du Pacifique étaient 
les pêches du hareng rogué à la senne et au filet maillant,
avec une prise combinée à l’échelle de la côte de `r total_final_yr_roe_catch` tonnes (t).
Dans la pêche du hareng-appât à la senne, les prises totales à l’échelle de la côte étaient de
`r total_final_yr_other_catch`&nbsp;t.
Les pêches de hareng rogué, de hareng-appât et de hareng aux fins d’usages spéciaux ont eu lieu dans la région du détroit de Géorgie uniquement en `r this_season`.
Toutes les zones ont été fermées à la pêche commerciale des œufs sur varech en `r this_season`.

Un programme complet de vérification à quai existe pour toutes les pêches du hareng du Pacifique à des fins commerciales
et les données sur les prises validées qui en résultent sont incluses
dans le processus annuel de gestion des stocks pour toutes les pêches, à l’exception de celle des œufs sur varech.

L’exclusion des données de la pêche des œufs sur varech du processus annuel d’évaluation des stocks était
identifiée comme une incertitude importante dans le dernier examen du SCAS
relatif au cadre d’évaluation des stocks [@cleary2018].
Les recommandations visant à dissiper cette incertitude nécessiteront de quantifier
la mortalité à la mise en étang et les prélèvements (c.-à-d. les œufs) associés à la pêche des œufs sur varech.
Bien que ce travail soit en cours,
les résultats ne sont pas encore disponibles pour éclairer l’évaluation des stocks.

## Description du processus d’évaluation des stocks

Le modèle statistique des prises selon l’âge est ajusté aux
données sur les prises commerciales,
aux données sur les proportions selon l’âge dans les pêches et les relevés, et
à un indice de la biomasse reproductrice indépendant de la pêche pour estimer
la biomasse totale et la biomasse reproductrice,
la mortalité naturelle et
le recrutement.
Le poids selon l’âge annuel observé est estimé en dehors du modèle, et
la maturité selon l’âge est un paramètre d’entrée fixe.
En 2017, une version actualisée du modèle statistique des prises selon l’âge a été appliquée pour évaluer chacune des
`r number_to_word(length(major_regions_short))`
régions principales d’évaluation des stocks de hareng du Pacifique [@cleary2018].
Le principal changement par rapport au modèle statistique des prises selon l’âge utilisé de 2011 à 2016 était
le partage de l’écart entre l’erreur d’observation et l’erreur de procédure
pour améliorer l’estimation de la structure de l’écart [@cleary2018].
Une analyse de rapprochement a été utilisée pour valider le modèle actualisé:
l’analyse a montré que les estimations des paramètres et les trajectoires de la biomasse
associées aux ajustements structurels sont presque identiques
aux résultats des versions précédentes du modèle,
ce qui appuie l’adoption de la structure révisée [@cleary2018].

Un cadre bayésien a été utilisé pour estimer des séries chronologiques de
la biomasse du stock reproducteur,
la mortalité naturelle instantanée et
le recrutement à l’âge `r age_first` entre `r major_start_yr` et `r major_end_yr`.
Les avis aux gestionnaires concernant les principales régions d’évaluation des stocks comprennent des estimations a posteriori de
l’état actuel du stock ($\SB_{`r major_end_yr`}$),
de l’état du stock par rapport au PRL de $0,3\SB_0$, et de
la biomasse du stock reproducteur en `r major_end_yr + 1` en supposant des prises nulles
($\SB_{`r major_end_yr + 1`}$).
La biomasse prévue du stock reproducteur est basée sur
les écarts de recrutement de l’année en cours par rapport à la moyenne, selon 
les prédictions du modèle de recrutement des stocks de Beverton-Holt, et
sur les estimations de la mortalité naturelle et du poids selon l’âge,
dont la moyenne pour chacune est calculée sur les 5 dernières années.
La procédure d’échantillonnage selon la méthode de Monte-Carlo par chaîne de Markov (MCMC)
suit la même méthode que celle mise en œuvre par @cleary2018.

@cleary2018 ont présenté les résultats de deux ajustements du modèle statistique des prises selon l’âge qui différaient sur le plan des hypothèses sur la capturabilité des relevés en plongée $q_2$ 
(de `r new_surv_yr` à `r major_end_yr`):
le modèle d’évaluation 1 (ME1) où $q_2$ est
estimé avec une distribution antérieure supposée; et
le modèle d’évaluation 2 (ME2) où $q_2 = 1$.
Les hypothèses selon lesquelles l’indice du frai lors des relevés en plongée représente
tout le frai déposé et qu’aucun œuf n’est perdu à cause de la prédation sont solides.
Cependant, les données d’évaluation des stocks contiennent peu d’informations
pour établir une estimation de $q_2$;
l’examen de la probabilité a posteriori de Bayes montre que la valeur a priori n’est pas mise à jour pour
les régions d’évaluation des stocks de HG, de la CC, du DG et de la COIV, et
que la valeur estimée reflète la valeur a priori [@cleary2018, Appendix D].
En supposant que $q_2 = 1$ produise une estimation «minimale» de la biomasse
atténuant toute autre erreur de mise en œuvre dans l’évaluation et la gestion
[@martell2011; @herring2012].
L’application du ME1 supprimerait ces précautions
en dépit d’une récente évaluation par simulation montrant que
des erreurs d’évaluation importantes (positives) sont produites par le modèle d’évaluation actuel,
même avec $q_2 = 1$ [@dfo2019a].
La mise à l’échelle de l’évaluation avec des valeurs de $q_2 < 1$ est susceptible de se traduire par
des erreurs d’évaluation absolues plus importantes que celles estimées
quand $q_2 = 1$ [@dfo2019a].
Pour ces motifs,
les avis présentés ici sont basés sur la paramétrisation du ME2,
soutenus également par les comparaisons présentées dans @dfo2016 [, tableau A1], et
@cleary2018 [, annexe D].
