\needspace{0.35\textheight}

# Collaborateurs

```{r, echo=FALSE, include=FALSE}
contributors <- tibble::tribble(
  ~"Collaborateur",         ~"Organisme d'appartenance",                        ~"Rôle",
  "Jaclyn Cleary",          "Secteur des sciences du MPO, région du Pacifique", "Auteur",
  "Sarah Power",            "Secteur des sciences du MPO, région du Pacifique", "Auteur",
  "Matthew Grinnell",       "Secteur des sciences du MPO, région du Pacifique", "Auteur",
  "Jennifer Boldt",         "Secteur des sciences du MPO, région du Pacifique", "Auteur (Ecosystem section)",
  "Chris Rooper",           "Secteur des sciences du MPO, région du Pacifique", "Auteur (Ecosystem section)",
  "Thomas Doniol-Valcroze", "Secteur des sciences du MPO, région du Pacifique", "Données (section Écosystémiques)",
  "Andrew Edwards",         "Secteur des sciences du MPO, région du Pacifique", "Données (section Écosystémiques)",
  "Moira Galbraith",        "Secteur des sciences du MPO, région du Pacifique", "Données (section Écosystémiques)",
  "Ian Perry",              "Secteur des sciences du MPO, région du Pacifique", "Données (section Écosystémiques)",
  "Strahan Tucker",         "Secteur des sciences du MPO, région du Pacifique", "Données (section Écosystémiques)",
  "Brianna Wright",         "Secteur des sciences du MPO, région du Pacifique", "Données (section Écosystémiques)",
  "Sam Johnson",            "Landmark Fisheries Research",                      "Données (section Écosystémiques)",
  "Katherine Middleton",    "Conseiller scientifique du MPO, Ottawa",           "Infographie (section Écosystémiques)",
  "Bryan Rusch",            "Gestion des pêches du MPO, région du Pacifique",   "Client",
  "Marisa Keefe",           "Gestion des pêches du MPO, région du Pacifique",   "Client")
```

```{r, results='asis'}
csasdown::csas_table(x = contributors, format = "latex") %>%
   row_spec(0, bold = TRUE) %>%
   column_spec(2, width = "7.5cm") %>%
   column_spec(3, width = "3.5cm")
```

<!-- Omit Contributors from table numbering -->
\addtocounter{table}{-1}
