<!-- For the pre-pub -->
<!-- \textblockcolour{yellow} -->
<!-- \textblockrulecolour{black} -->
<!-- \begin{textblock*}{0.55\textwidth}(12cm,0.3cm) -->
<!-- This document is approved and in pre-publication with CSAS. -->
<!-- As such it is confidential in nature and -->
<!-- cannot be distributed more broadly or -->
<!-- shared with the public on the CSAS website. -->
<!-- \end{textblock*} -->

# CONTEXT\label{sec:context}

Pacific Herring (*Clupea pallasii*) abundance in British Columbia (BC) is
assessed using a statistical catch-age (SCA) model [@martell2011].
In 2017, the Pacific Herring stock assessment included
updates to the SCA model, a bridging analysis 
to support these changes [@cleary2018], and 
estimation of stock productivity and current stock status
relative to the new limit reference point (LRP) of $0.3\SB_0$ [@kronlund2017],
where $\SB_0$ is estimated unfished spawning biomass.
In 2022, upper stock reference (USR) point options
were introduced for the major stock assessment regions (SARs) and
this assessment includes estimates of stock status relative to
productive period USRs [@dfo2022a].
The overall structure of the SCA model has not changed since 2017.

In 2016, Fisheries and Oceans Canada (DFO) committed to
renewing the current management framework to address
a range of challenges facing Pacific Herring stocks and fisheries in BC.
Renewal of the management framework included engaging in
a management strategy evaluation (MSE) process to evaluate
the performance of candidate management procedures against
a range of hypotheses about future stock and fishery dynamics.
As part of the MSE process,
a Canadian Science Advisory Secretariat (CSAS)
regional peer review occurred in 2018,
where performance of Pacific Herring management procedures (MPs) were assessed
against conservation objectives for the
Strait of Georgia (SoG) and West Coast of Vancouver Island (WCVI)
SARs [@dfo2019a].
Steps included operating model (OM) development [@benson2022],
fitting the OM to Pacific Herring stock and fishery monitoring data
(OM conditioning), and
closed-loop simulations of MP performance for alternative
future natural mortality scenarios.
In 2019, DFO initiated the MSE process for the
Haida Gwaii (HG), Prince Rupert District (PRD), and Central Coast (CC)
SARs [@dfo2019c].
Updates to MP evaluations were then conducted for
SoG and WCVI SARs in 2020 [@dfo2021b] and
for PRD, CC, SoG, and WCVI in 2023 [@dfo2022a; @dfo2022b].

This assessment includes new science advice on choice of USR points for
`r number_to_word(length(major_regions_short[!major_regions_short %in% fsar_sars]))`
of the `r number_to_word(length(major_regions_short))` major
Pacific Herring SARs:
`r commify(major_regions_short[!major_regions_short %in% fsar_sars])`.
Note that the `r commify(fsar_sars)` SARs are assessed in
<!-- TODO: Update to @dfo2025c and @dfo2025d when published -->
DFO\footnote{\label{fn:dfo2025c}
DFO. In prep. Prince Rupert District Pacific Herring (Clupea pallasii)
stock status in 2025 and forecast for 2026.
DFO Can. Sci. Advis. Sec. Sci. Advis. Rep.}
and DFO\footnote{\label{fn:dfo2025d}
DFO. In prep. Strait of Georgia Pacific Herring (Clupea pallasii)
stock status in 2025 and forecast for 2026.
DFO Can. Sci. Advis. Sec. Sci. Advis. Rep.}
respectively, using a new modelling framework [@johnson2024].
An analysis of USR options for PRD, CC, SoG, and WCVI was completed in 
2022 [@dfo2022a] and provisional USRs based on productive 
periods identified for each SAR was implemented in the 2022/23 Integrated 
Fisheries Management Plan (IFMP).
Note that Haida Gwaii USRs are developed in the
HG rebuilding plan process.\footnote{\label{fn:rebuild}
Haida Gwaii 'íináang | iinang Pacific Herring:
An ecosystem overview and ecosystem-based rebuilding plan.
Approved by the Minister of Fisheries and Oceans, the Council of Haida Nation 
and Parks Canada. April 2024. In Press.}

Since initiation of the Pacific Herring MSE process,
MP evaluations have been included in the annual stock assessment as follows:

1. The 2018 stock assessment included
MP recommendations for the SoG and WCVI SARs [@dfo2019a].

1. The 2019 stock assessment included
MP recommendations for the HG, PRD, and CC SARs, and
implemented MP recommendations from previous years for the
SoG and WCVI SARs [@dfo2020a].

1. The 2020 stock assessment included
updated MP recommendations for the SoG and WCVI SARs, and
implemented MP recommendations from previous years for the
HG, PRD, and CC SARs [@dfo2021b].

1. The 2021 stock assessment included
updated MP recommendations for the PRD and CC SARs, and
implemented MP recommendations from previous years for the
SoG and WCVI SARs [@dfo2021c].

1. The 2022 stock assessment included
updated MP recommendations for the PRD, CC, SoG, and WCVI SARs [@dfo2022b].

1. The 2023 stock assessment implemented
MPs from previous years for the PRD, CC, SoG, and WCVI SARs [@dfo2024].
Management measures to support long-term recovery of HG herring 
are developed through the HG rebuilding plan process.$^{\ref{fn:rebuild}}$

1. The 2024 stock assessment implemented
MPs from previous years for the PRD, CC, and WCVI SARs [@dfo2025a].

1. MPs for SoG are updated in @dfo2025b using methods from @johnson2024
and applied in 2024 and 2025 (DFO, In prep.).$^{\ref{fn:dfo2025d}}$

1. MPs for PRD are updated in DFO (In prep.).$^{\ref{fn:dfo2025c}}$

1. The 2026 stock assessments for HG, CC, and WCVI
will be implemented in SISCAH.

This `r assess_yr` stock assessment includes
MP recommendations for CC and WCVI,
derived in 2022 by updating herring OM conditioning [@benson2022] using 
the historic stock and fishery data
from `r major_start_yr` to 2021 [@dfo2022b].
There are no new MP evaluations for `r assess_yr`
(all probability metrics reflect the MP evaluations presented in 2022).

Fisheries and Oceans Canada (DFO) Pacific Fisheries Management Branch requested
that DFO Pacific Science Branch assess the status of
British Columbia (BC) Pacific Herring stocks in `r assess_yr` and
recommend harvest advice for `r assess_yr + 1`
using simulation-tested MPs to inform the development of the
`r assess_yr`/`r assess_yr + 1` IFMP, where appropriate.
Estimated stock trajectories,
current status of stocks for `r assess_yr`,
management procedure options, and
harvest advice recommendations from those MPs for `r assess_yr + 1`
reflect methods of @cleary2018 and @benson2022 and,
where applicable,
recommendations from the aforementioned
2018, 2019, 2020, 2021, 2022, and 2023 MSE analyses
(Section "\nameref{sec:harv-opts}").

<!-- Mandatory last paragraph in this section -->
This Science Response results from the regional peer review of
`r t_process_month` `r rmarkdown::metadata$process_day`,
`r rmarkdown::metadata$process_year` on `r rmarkdown::metadata$title`.
