# Background

Pacific Herring in BC are managed as
`r number_to_word(length(major_regions_short))` major and
`r number_to_word(length(minor_regions_short))` minor
SARs (Figure \@ref(fig:bc-map)).
The major SARs are `r commify(major_regions_full_parens)`.
The minor SARs are `r commify(minor_regions_full_parens)`.
We conduct formal analyses of stock trend information for the major SARs.
Recall that the SoG assessment is in @dfo2025b.
For the minor SARs, we present available
catch data, biological data, and spawn survey data
(Section "\nameref{sec:app-minor}").
Beginning in 2021 we include similar data for the special area, Area 10
(Section "\nameref{sec:app-special}").
Note that Area 10 is a subset of the Central Coast
and is outside the SAR boundary.
Formal analyses of stock trends are not included for
minor SARs or special areas.

## Description of the fishery

There are several Pacific Herring fisheries in BC.
After conservation,
First Nations have priority access to fish for
food, social, and ceremonial (FSC) purposes.
Commercial fishing opportunities consist of four directed fisheries:
food and bait (FB),
special use (SU),
spawn-on-kelp (SOK), and
roe herring.
There is also a small recreational fishery.

First Nations fish for whole herring, herring roe, and
herring eggs for FSC purposes.
Whole herring are fished by seine, gillnet, rake, dip net, and jig.
Herring eggs are collected as spawn on seaweed such as kelp (i.e., SOK), or
spawn on tree boughs placed in spawning locations. 
Indigenous harvest of herring for FSC purposes may occur coast wide
where authorized by a communal licence.

In addition, treaty and Aboriginal commercial fisheries may occur
in some specific management regions.
Four modern treaties (Nisga'a, Tsawwassen, Maa-nulth, and Tla'amin)
have been ratified in BC and articulate a treaty right to FSC harvest of fish.
Five Nuu-chah-nulth First Nations located on the West Coast of Vancouver Island
-- Ahousaht, Ehattesaht, Hesquiaht, Mowachaht/Muchalaht, and Tla-o-qui-aht
(the Five Nations) --
have Aboriginal rights to fish for any species of fish,
with the exception of Geoduck,
within their Fishing Territories and to sell that fish.
DFO developed a 2022/23 Five Nations Multi-Species
Fishery Management Plan (FMP).
The FMP includes specific details about the fishery, such as
allocation/access,
licensing and designations,
fishing area,
harvesting opportunities, and
fishery monitoring and catch reporting.
Feedback provided by the Five Nations during consultations was considered
and incorporated into the 2023/24 FMP by DFO where possible.
For further information see the 2023/24
\link{https://waves-vagues.dfo-mpo.gc.ca/library-bibliotheque/41096605.pdf}{FMP}.

On the Central Coast,
Heiltsuk Nation have an Aboriginal right to commercially harvest
Pacific Herring SOK.
The Heiltsuk currently hold nine SOK licences in this area,
and SOK is harvested using the preferred means of the Heiltsuk,
which is open ponding.
The DFO and Heiltsuk are also committed to annual development of a
Joint Fisheries Management Plan for Pacific Herring in the Central Coast.

In `r this_season`, the primary Pacific Herring fisheries were 
seine roe and gillnet roe fisheries,
with a combined coast wide catch of `r total_final_yr_roe_catch` tonnes (t).
The FB seine fishery had a coast wide catch of
`r total_final_yr_other_catch`&nbsp;t.
The roe fisheries operated in SoG and PRD this season, and FB and SU fisheries
in SoG only.
Commercial SOK fisheries operated only in the CC in `r this_season`.

A complete dockside monitoring program exists for all Pacific Herring
commercial fisheries and the resulting validated catch data are included
in the annual stock assessment process for all fisheries, except SOK.

The exclusion of SOK fishery data from the annual stock assessment process was
identified as a key uncertainty in the most recent CSAS review
of the stock assessment framework [@cleary2018].
Recommendations for addressing this uncertainty will require quantifying
ponding mortality and removals (i.e., eggs) associated with SOK fisheries.
Progress has been made in quantifying SOK mortality sources within the 
new modelling framework [@dfo2023a], however those approaches are not
transferable to the SCA model [@martell2011] used here.

## Description of the stock assessment process

The SCA model is fitted to
commercial catch data,
fishery and survey proportion-at-age data, and
a fishery-independent spawning biomass index to estimate
total and spawning biomass,
natural mortality, and
recruitment.
Observed annual weight-at-age is estimated external to the model, and
maturity-at-age is a fixed input parameter.
In 2017, an updated version of the SCA model was applied to assess each of the
`r number_to_word(length(major_regions_short))`
major Pacific Herring SARs [@cleary2018].
The main change from the SCA model used from 2011 to 2016 was
the partitioning of variance between observation and process error
to improve the estimation of the variance structure [@cleary2018].
A bridging analysis was used to validate the updated model:
this showed parameter estimates and biomass trajectories
associated with the structural adjustments to be nearly identical
to results from previous versions of the model,
supporting the adoption of the revised structure [@cleary2018].

A Bayesian framework is used to estimate time series of
spawning biomass,
instantaneous natural mortality, and
age-`r age_first` recruitment from `r major_start_yr` to `r major_end_yr`.
Advice to managers for the major SARs includes posterior estimates of
current stock status $\SB_{`r major_end_yr`}$,
stock status relative to the LRP of $0.3\SB_0$, and
spawning biomass in `r major_end_yr + 1` assuming no catch
$\SB_{`r major_end_yr + 1`}$.
The projected spawning biomass is based on
the current year's recruitment deviations from average as 
predicted by the Beverton-Holt stock-recruit model, and
estimated natural mortality and weight-at-age,
both averaged over the most recent 5-years.
The Markov chain Monte Carlo (MCMC) sampling procedure
follows the same method implemented by @cleary2018.

@cleary2018 reported results from two SCA model fits that differed
in assumptions about dive survey catchability $q_2$
(from `r new_surv_yr` to `r major_end_yr`):
assessment model 1 (AM1) where $q_2$ is
estimated with a prior distribution assumed; and
assessment model 2 (AM2) where $q_2 = 1$.
The assumptions that the dive survey spawn index represents
all the spawn deposited and that no eggs are lost to predation are strong.
However, there is little information in the stock assessment data
to inform an estimate of $q_2$;
examination of the Bayes posterior shows the prior is not updated for
the HG, CC, SoG, and WCVI SARs, and
estimated values reflect the prior means [@cleary2018, Appendix D].
Assuming $q_2 = 1$ produces a "minimum" biomass estimate
buffering any other assessment and management implementation errors
[@martell2011; @herring2012].
Application of AM1 would remove such safeguards
despite recent simulation evaluation showing that
large (positive) assessment errors are produced by the current assessment model
even with $q_2 = 1$ [@dfo2019a].
Scaling the assessment with values of $q_2 < 1$ is likely to result in
larger absolute assessment errors than those estimated
when $q_2 = 1$ [@dfo2019a].
For these reasons,
advice presented here is based on the AM2 parameterization,
supported also by comparisons presented in @dfo2016 [, Table A1], and
@cleary2018 [, Appendix D].
