# Analysis and response

## COVID-19 pandemic

Compared to 2020, the COVID-19 pandemic had fewer impacts
to Pacific Herring data collection and analysis in 2021.
Spawn surveys proceeded as usual in most areas in 2021,
with dive surveys in all major areas except Haida Gwaii.
Haida Gwaii would normally have a dive survey,
but had a surface survey in 2021 due to COVID-19.
The collection and analysis of biological data was not affected
by the COVID-19 pandemic in 2021.

## Management strategy evaluation

Fisheries and Oceans Canada (DFO) has committed to
renewing the current management framework to
address a range of challenges facing Pacific Herring stocks and fisheries
in British Columbia. 
Renewal of the management framework for Pacific Herring uses MSE to
evaluate the performance of candidate MPs against
hypotheses about past and future stock and fishery dynamics. 
The purpose of the MSE process is to
identify MPs that provide acceptable outcomes related to
conservation and fishery management objectives. 
The identification of a preferred management procedure requires
a fully specified set of measurable objectives that include
reference points (typically categorized as limits and targets) and
to the extent possible,
specification of objectives related to
catch, catch variability, and socio-cultural goals. 
MSE is an iterative and ongoing process conducted with the participation of
First Nations, the fishing industry, as well as
government and non-government organizations. 

The first MSE cycles for the SoG and WCVI management areas were completed in 2018 [@dfo2019a].
Steps included
OM development,
fitting the OMs to Pacific Herring stock and fishery monitoring data
from 1951 to 2017, and
closed-loop simulations of MP performance for
alternative future natural mortality scenarios [@dfo2019a].
In the spring of 2019,
the MSE process was extended to the HG, PRD, and CC management areas
with stock and fishery monitoring data updated to include 2018
and performance evaluation of area specific MPs [@dfo2019c].
In the summer of 2020,
the second MSE cycle was initiated for the WCVI and SoG management areas.
This included conditioning the OMs with more recent stock and fishery data, and
evaluating the performance of additional candidate MPs
for these management areas.
A similar update was conducted in the summer of 2021
for the PRD and CC management areas.
Results from MP evaluations reflect most recent updates for all management areas.

A core set of fisheries management objectives [@dfo2019c] have been applied to each major SAR:

1. Maintain spawning biomass above the LRP with at least 75% probability
over three Pacific Herring generations
(i.e., avoid a biomass limit; $P(\SB_t > 0.3\SB_0) \geq 0.75$),

1. Maintain spawning biomass at or above the USR with at least 50% probability 
over three Pacific Herring generations
(i.e., achieve a target biomass; $P(\SB_t \geq 0.6\SB_0) \geq 0.5$),

1. Maintain average annual variability (AAV) in catch below 25%
over three Pacific Herring generations
(goal reflecting catch variability; $\text{AAV} < 0.25$), and

1. Maximize average annual catch
over three Pacific Herring generations
(goal reflecting catch biomass).

However, a fully specified set of objectives has not yet been developed
for each management area.
DFO will continue to collaborate with coastal First Nations to
develop area-specific objectives specific to
Food, Social and Ceremonial fisheries as well as
spawn-on-kelp (SOK) fisheries.
In addition, DFO will continue to engage with
the herring industry, government, and non-government organizations
to describe broader objectives related to conservation, economics, and access.

The MPs for each SAR differ in the form of the HCR and choices of catch cap,
but use the same type of monitoring data and assessment model
[e.g., @cleary2018].
The current stock assessment model assumes natural mortality is
time-varying and this is reflected in the MSE as
three hypotheses about future Pacific Herring natural mortality $M$: 

1. $M$ is a time-varying, density-dependent process (DDM),

1. $M$ is a time-varying, density-independent process (DIM), and

1. $M$ is constant over time (conM).

These three hypotheses are captured as three operating model (OM) scenarios in @dfo2019a.
The DDM scenario was identified as the Reference OM scenario based on
discussion at the July 2018 CSAS review process [@dfo2019c],
while the DIM and conM scenarios were identified as Robustness OM scenarios.
There is however currently no scientifically supported method to
predict natural mortality;
thus all three scenarios are included. 

Several lessons were learned from the MSE analyses conducted so far:

1. The catch-at-age stock assessment model can produce large (positive)
assessment errors.
Such assessment errors cause over-estimation of spawning biomass and
result in recommended catch limits such that the realized harvest rate exceeds
the intended target specified by a HCR (e.g., over-harvest).

1. Reduction in harvest rate from 20% to 10% was the most effective means of
mitigating stock assessment errors by
reducing the absolute size of the catch.
The use of a catch cap, implemented as a maximum annual catch level, 
is an effective model-free way to
further mitigate assessment errors at very high biomass levels.
Simulation analyses additionally showed that outcomes
are insensitive to the choice of operational control points (OCPs)
in the HCR when a low harvest rate (HR) and catch cap are applied.
This occurs because low biomass levels (associated with the lower OCP)
are avoided for these MPs.

1. Differences in specification of Pacific Herring MPs,
including HCR components, are expected a priori among SARs.
The reasons relate to
differences in objectives deemed important by resource users,
differences in historical and current stock and fishery dynamics, and
differences in the magnitude and direction of assessment model errors in each SAR.
Conservation objectives such as those based on
avoiding a threshold to serious harm (i.e., a limit reference point) 
in alignment with the DFO PA Framework [@dfo2009] are held constant among SARs
based on the analyses of @kronlund2017.

1. There are many possible ways to incorporate MP performance in
robustness trials into decision-making but, 
there is currently no accepted scientific way of
combining results from multiple operating models.

1. In situations where multiple MPs meet the agreed upon objectives,
further criteria, such as ranking secondary objectives, is needed in order to
provide decision-makers with a tractable set of trade-off choices.

1. Outcomes of MP evaluations appear to be more heavily influenced by
the last three to five years of stock status and 
natural mortality trends used to condition the OM. 
If simulations were run over a greater number of years (e.g., 50 years)
performance would start to approach equilibrium and be 
unaffected by most recent trends in OM conditioning data.

## Input data

There are three types of input data used for the Pacific Herring stock assessment:
catch data, biological data, and abundance data.
These data sets are described in the following sections, and
summarized in Table \@ref(tab:data-input).
Relative to the previous assessment,
the only change made to input data was to update all data time series
to include data from the `r this_season` herring season (July 1 to June 30).
Note that we refer to 'year' instead of 'herring season' in this report;
therefore `r assess_yr` refers to the `r this_season` Pacific Herring season.

### Catch data

For the purposes of stock assessment,
catch data are summarized by gear type as described in
Table \@ref(tab:data-input) and presented in Figure \@ref(fig:major-catch).
As in previous years, catch input to the stock assessment model
does not include mortality from the commercial SOK fishery,
nor any recreational fisheries or food, social, and ceremonial (FSC) harvest.
The FSC and recreational harvest are considered minor relative to commercial harvest.
The commercial SOK fishery is licensed based on pounds of validated SOK product
(i.e., eggs adhered to kelp), not tonnes of fish used or spawned.
Currently there is no basis for validating mortality
imposed on the population by this fishery, however
methods for estimating SOK mortality are being developed.

Combined commercial removals from `r assess_yr-9` to `r assess_yr`
from the roe, food and bait, and special use fisheries
appear in Table \@ref(tab:annual-catch).
The proportion of coast-wide catch that comes from SoG was
22% in 1990, and 100% in `r assess_yr`.
Total SOK harvest (pounds of validated product) for the major SARs
from `r assess_yr-9` to `r assess_yr` is presented in
Table \@ref(tab:annual-sok-catch).

### Biological data\label{sec:biol-data}

Biological samples are collected as described in
@cleary2018 and Table \@ref(tab:data-input).
Biological data inputs to the stock assessment are
annual weight-at-age (Figure \@ref(fig:major-wa)) and 
annual number-at-age, shown as proportion-at-age (Figure \@ref(fig:major-pa)).

Significant declines in weight-at-age are evident for all major herring stocks,
from the mid-1980s to 2010.
Declining weight-at-age may be attributed to any number of factors, including
fishing effects (i.e., gear selectivity),
environmental effects (e.g., changes in ocean productivity), or
changes in sampling protocols (e.g., shorter time frame over which samples are collected).
There has been an increasing trend in weight-at-age for all major stocks
from 2012 to `r assess_yr`,
although to a lesser degree for PRD.

### Abundance data

The spawn index survey collects information on
spawn length (i.e., distance parallel to shore),
spawn width (i.e., distance perpendicular to shore),
number of egg layers by vegetation type, and
other data.
There are two spawn survey periods defined by the predominant survey method:
surface survey period from `r surv_yr_rng[1]` to `r new_surv_yr - 1`, and
dive survey period from `r new_surv_yr` to `r surv_yr_rng[2]`.
Data from these surveys are used to calculate egg densities per spawn.
Ultimately, the estimated weight of mature spawners required
to produce the egg deposition is calculated and
referred to as the 'spawn index'.
The `r surv_yr_rng[2]` spawn survey followed standard dive survey protocols
for the PRD, CC, SoG, and WCVI SARs as described in @cleary2018, and
a surface survey protocol for the HG SAR due to COVID-19.
Time series of spawn index by major stock assessment region (SAR)
from `r paste(surv_yr_rng, collapse=" to ")`
are summarized in Figure \@ref(fig:major-spawn-index).
In `r surv_yr_rng[2]`, there was an
increase in survey biomass (i.e., index values) for the PRD and WCVI SARs, and
a decrease in survey biomass for HG, CC, and SoG SARs
(Figure \@ref(fig:major-spawn-index) and
Tables \@ref(tab:spawn-index-hg) to \@ref(tab:spawn-index-wcvi)).

## Spatial spawn distribution

Tables \@ref(tab:spawn-index-hg) through \@ref(tab:spawn-index-wcvi) 
summarize the spatial distribution of survey spawn biomass
(i.e., the spawn index)
by proportion over the most recent `r num_yrs_tab+1` years for the major SARs.
HG and SoG are summarized by Group, while
PRD, CC, and WCVI are summarized by Statistical Area;
the choice of spatial grouping reflects spawning behaviour and
biology for each SAR based on the
survey data and working group discussions with local First Nations.

## Incidental mortality

In order to advance progress towards
a holistic ecosystem-based management (EBM) approach for Pacific Herring
we present the information currently available
to describe indirect effects on herring populations,
such as incidental mortality. 
Some fisheries and aquaculture activities in BC cause
incidental mortality to Pacific Herring.
Similar to SOK harvest as well as FSC and recreational catch,
incidental mortality is currently only indirectly accounted for 
in Pacific Herring stock assessment by
estimating annual rates of natural mortality, 
and is considered minor relative to commercial harvest.

Again this year,
we include available data for incidental mortality in
finfish aquaculture activities
by SAR from `r min(ic_yrs)` to `r max(ic_yrs)`
(Figure \@ref(fig:major-incidental)).
Note that incidental mortality data are reported by
Pacific Fishery Management Area (PFMA)
which are analogous to Statistical Areas, but
PFMAs are larger and can extend beyond SAR boundaries.
Data indicate the number of Pacific Herring dead and released,
with the following caveats:

1. Data for `r max(ic_yrs)` are considered incomplete,

2. Unknown mortality rate for "released" fish,

3. Unknown length, weight, age, and sex of fish, and

4. "Herring-like" fish are assumed to be herring
when decomposition hinders identification.

Note that we sometimes update data in previous years
as DFO receives additional reports.

## First Nations observations

The COVID-19 pandemic continues to impact First Nations participation
in Pacific Herring survey activities as well as participation
in traditional harvest activities such as FSC.
<!-- Assembling local observations was not possible for the 2020 season, -->
<!-- however in 2021, local observations were provided by -->
<!-- coastal First Nations participants for most areas. -->
The following descriptions were provided by First Nations contributors.

### Haida Gwaii

<!-- The Selwyn and Cumshewa Inlets stock has seen steady declines over the past decade to the point where this past season there almost was no spawn to be found. -->
<!-- The spawn occurred very late in the season (late April) and was in outer Selwyn near Rockfish Harbour (rather than inside Selwyn near Traynor Bay).  -->
<!-- The spawn this year was considered to be fairly minimal for Selwyn Inlet standards and insufficient to extend into Cumshewa Inlet. -->

<!-- This year in the Skincuttle and Upper Burnaby area, the bulk of the spawning occurred on the Skincuttle side, but in other years it has occurred more north of the narrows in upper Burnaby Strait. -->
<!-- This stock is just barely maintaining itself. -->
<!-- Abundance is low enough that natural recruitment just barely makes up for natural mortality – so we see some years of slight recovery followed by other years of decline, but no real growth even in the absence of a fishery now in almost 20 years. -->

<!-- The Juan Perez Sound inlets normally will support spawns when there are a lot of recruits in the population and first time spawners can out number old repeat spawners. -->
<!-- That has not been the case now for some time. -->
<!-- Lately spawns have been small and infrequent in the inlets of Juan Perez Sound, as was the case in 2021. -->

<!-- There has not been a significant presence of herring abundance in outer Louscoone for a number of years now. -->
<!-- In years of abundance, the local stock was always found to be well up inside the inlet and often presented a very light spawn near the head in the early portion of the season (early to mid March). -->
<!-- This stock seldom exceeded 500 tons – however in recent years it has been much less. -->
<!-- The other stock appears to be more migratory- found in the outer portions of Louscoone Inlet and rarely spawns in Louscoone. -->
<!-- One theory is outer Louscoone is used as a staging area and that these herring would then migrate elsewhere (possibly to the Central Coast) to spawn. -->
<!-- Now, abundance is not high enough to allow herring to build up in outer Louscoone early in the season – so we only see evidence of the minor local stock. -->

<!-- There was some effort for the traditional harvest of k’aaw in both Skincuttle Inlet and Selwyn Inlet in early to mid April, 2021.  -->
<!-- The open kelp lines set up in Jedway Bay, Skincuttle Inlet, were successful with approximately 2,000 lbs of good quality k’aaw being harvested.  -->
<!-- The open kelp lines set up in the cove just south of Traynor Bay, Selwyn Inlet, were unsuccessful due to the absence of spawn.  -->
<!-- There were no other (known) attempts for the harvest of k’aaw on Haida Gwaii during the 2021 herring season. -->

### Prince Rupert District

<!-- Overall, very little spawn was observed this season by members and staff of the Lax Kw’alaams Band. -->
<!-- Lax Kw’alaams Fisheries Technicians, in coordination with Metlakatla Guardians, spent ten full days during the herring season monitoring harvest and recording herring behaviour and locations. -->
<!-- During the surveys, technicians were unable to locate herring schools in any of the normal geographic areas monitored each year. -->
<!-- This year in the Prince Rupert District, Lax Kw’alaams had several fishermen out on the water. -->
<!-- On-grounds correspondence with harvesters confirmed that herring spawn in the 2021 season was quite poor and ephemeral, and most reported seeing no active herring spawning in important harvest areas. -->
<!-- However, the FSC harvest incidentally reported spawn in a couple of areas and was more promising than previous years. -->
<!-- A few more community members were able to obtain some spawn-on-branches for the first time in many years, with sufficient layers to justify a small harvest. -->
<!-- However, Lax Kw’alaams fishermen were unable to gather enough herring to satisfy FSC needs for the majority of the community. -->

### Central Coast

FSC harvesters in Area 08 observed only brief spot spawns
lasting 24 hours or less.
Field observation confirmed egg thickness on kelp and branches
was limited to one layer for the most part.
Herring observed in spawning aggregations were small in size.

<!-- Observations in Area 06: The overall herring spawn continued to improve in 2021 as the stock has continued to build over the past few years. -->
<!-- Kitasu Bay appeared to have similar or higher abundance that 2020. -->
<!-- Herring sizes were typical for the area but seemed to be more uniform in overall size. -->
<!-- The spawn was longer than average with 7 to 8 days of continuous spawn that appeared to cover much of Kitasu Bay. -->
<!-- The sea lion activity was significant as in previous years but due to the high abundance of herring, sea lions appeared to avoid the -->
<!-- herring ponds which in previous years were directly targeted by feeding sea lions. -->
<!-- The community food gathering was successful for both spawn on branch and there was some surplus from SOK operations to support the community as well. -->
<!-- Kelp size and quality was very good in the Bay as compared to previous years. -->

<!-- Observations in Area 07: The 2021 herring season saw drastic changes to the herring spawning patterns,  -->
<!-- yield and roe thickness compared to previous years. -->
<!-- The normal pattern for the herring spawning is when herring spawn in one location for 5 to 7 days in specific areas. -->
<!-- This season the herring were spawning very sporadically and for short periods of time. -->
<!-- In most areas the spawn would last only for a day and then herring would move to another location. -->

<!-- Predation by whales, seals, and sea lions has increased dramatically in the last 20 years and more so in the last few years  -->
<!-- causing shifts in spawning behaviour and patterns.  -->
<!-- Fishers observed multiple whales right up in the shallows feeding on the herring and disrupting or stopping the spawn. -->

<!-- Most of the spawning in the Spiller area was limited to inside and outside of the Tate Lagoon area with  -->
<!-- minimal spawning in the rest of Spiller area.  -->
<!-- Inside Tate Lagoon, the average layers were generally around 3 to 4 layers. -->
<!-- Fishers set kelp in every identified spawn location including -->
<!-- Spiller, Thompson, Norman Morrison, Dundavin,  -->
<!-- Idol, Foote, mid Spiller, Bachelor, Berry, and Mustang Bay -->
<!-- all of which saw an average of 2 to 3 layers. -->

<!-- Our fishers reported that despite having kelp set at multiple spawn areas, the herring observed were smaller  -->
<!-- on average and the layers of roe on the kelp was minimal indicating smaller spawning herring.  -->
<!-- The build up of roe took long and averaged only 2 to 3 layers.  -->

<!-- The consensus among fishers and management was that this year was worse than the previous two years  -->
<!-- and were unable to attain sufficient FSC or fulfill our herring roe spawn on kelp quota despite a lot of effort.  -->

### Strait of Georgia

<!-- In the Northern SoG, A-Tlegay Fisheries assisted the herring assessment program by providing additional dive survey coverage and attempting to collect cast net samples on active spawns.  -->
<!-- A-Tlegay divers surveyed spawn from Willow Point south down to Bates Beach (and beyond), Herring Sections 135 and 141. -->
<!-- Through an outreach program, spawns were also reported to A-Tlegay from local mainland inlet areas. -->
<!-- As a result, A-Tlegay was able to dive on two spawns in Bute Inlet and 1 spawn in Teakerne Arm (Section 151). -->

### West Coast of Vancouver Island

<!-- In general, herring spawn was sporadic and short in duration in Barkley and Nootka Sounds with a spawn lasting several days in Hesquiaht Harbour.  -->

<!-- In Nootka, herring were in the deep off of Yuquot for a couple of weeks and then they moved outside to Bajo Reef/Beano Creek area in mid-March. -->
<!-- Bird and marine mammal activity shifted from the vicinity of Yuquot out to Bajo/Beano area. -->
<!-- Ray Williams of Yuquot reported a small spawn in the lower end of Tahsis Inlet, but it could not be located by the spawn reconnaissance crew. -->
<!-- There was a small harvest of spawn on kelp (60 lb total) just off the rocks of Escalante.  -->

<!-- There was a small spawn in the shallows in the Port Langford area of Nuchatlitz on March 9^th^ and later in Rosa Harbour. -->
<!-- Only 20% of the trees set for spawn-on-bough collections were successful in the area.  -->

<!-- In Area 23, the spawns were small and short in duration around mid-March. -->
<!-- The main spawn was around Muscle Beach to Macoha on March 12^th^. -->
<!-- Most trees set for spawn-on-boughs collections reported having mostly 2 to 4 layers of eggs and were set back in the water to hatch. -->

<!-- There were several trees for home use set by First Nations at this active spawn during sample collections. -->
<!-- Activity was noted in front of the beach North and South of Maggie River but they did not appear to be actively spawning. -->
<!-- Other spawn investigated around this time was at Mussel beach. -->
<!-- At the end of March a small spawn was reported at Lyall point.  -->

<!-- In Area 24, most spawning activity was in and around Hesquiaht Harbour from about the first week in March until near the end of the month. -->
<!-- Hesquiaht Harbour is not a great area for SOB due to the prevalence of sandy bottom substrates and windy conditions.  -->

## Stock status update

Analyses of stock trend information for AM2 are presented following
methods of @cleary2018 for the Pacific Herring major SARs.
As in previous years,
MCMC runs have chain length `r f(mcmc_length)`
with a sample taken every `r f(mcmc_samp_freq)`^th^ iteration (i.e., thinning).
The first `r f(mcmc_burnin)` samples are discarded (i.e., burn-in),
leaving `r f(mcmc_num_samples)` samples for posteriors.
Perceptions of stock status based on outputs (i.e., posteriors)
from the SCA model (AM2)
are summarized for each stock in a multi-panel figure
(e.g., Figure \@ref(fig:storyboard-hg)).
The panels show:

a. Model fit to scaled spawn survey data,

a. Instantaneous natural mortality rate $M$ estimates,

a. Number of age-`r age_first` recruits,

a. Spawning biomass $\SB_t$ and total catch $C_t$ in year $t$,
with reference lines at model estimates of $0.3\SB_0$,

a. Recruitment deviations (log scale) from the
Beverton-Holt recruitment function, and

a. Spawning biomass production $P_t = \SB_{t+1} - \SB_t + C_{t+1}$
for the dive survey period,
with reference lines at model estimates of $0.3\SB_0$.

Note that spawn survey data (i.e., spawn index) is scaled to abundance
in panel (a) by the spawn survey scaling parameter $q$.
The spawn index has two distinct periods defined by the dominant survey method: 
surface surveys (`r surv_yr_rng[1]` to `r new_surv_yr - 1`), and 
dive surveys (`r new_surv_yr` to `r surv_yr_rng[2]`).
Thus, two $q$ parameters are implemented in the estimation procedure:
$q_1$ (`r surv_yr_rng[1]` to `r new_surv_yr - 1`)
with an uninformative prior, and
$q_2$ (`r new_surv_yr` to `r surv_yr_rng[2]`)
with an informative prior approximating 1.0.

The surface survey methodology has been used on occasion
from `r new_surv_yr` to `r surv_yr_rng[2]`. 
Generally this occurs when herring spawn is observed in locations where
a dive survey team is not available, or
when spawning occurs very early (e.g., January or February) or
late (e.g., May) in the season. 
In these instances,
spawning biomass estimates obtained from surface surveys for
a given stock area and year are added to
biomass estimates from dive surveys,
and $q_2 = 1$ is assumed for the combined index.
In 2020 and `r surv_yr_rng[2]`,
a full surface survey was conducted for the HG SAR and
in this assessment the resulting survey biomass estimates are
assumed continuous with the dive survey time series.

### Reference points\label{sec:ref-pts}

A biological limit reference point (LRP) is defined for the major
Pacific Herring SARs at $0.3\SB_0$ [@kronlund2017].
Candidate upper stock references (USR) were introduced in @cleary2018 and
implemented as biomass objectives in the simulation analyses for WCVI and SoG
in 2018 [@dfo2019a] and then for HG, PRD, and CC in 2019 [@dfo2019c].
Candidate USRs are:

1. $0.4\SB_0$,

1. $0.6\SB_0$,

1. Average spawning biomass from `r major_start_yr` to `r assess_yr`,
$\SB_{\mli{ave}}$, and

1. Average spawning biomass during a productive period [@cleary2018],
$\SB_{\mli{ave-prod}}$.

Simulation results showed similar properties between USRs
$0.6\SB_0$ and $\SB_{\mli{ave}}$ both within and among SARs,
while the USR based on the average biomass in a productive period,
$\SB_{\mli{ave-prod}}$, was found to be most variable among SARs.
The simulation-evaluations did not select a single USR,
however a USR of $0.6\SB_0$ is included in this stock status update because
this candidate is sufficiently above the LRP (2*LRP) and
it is a repeatable calculation across all SARs.
Stock status relative to the assessment model estimates $0.3\SB_0$ (LRP) and
$0.6\SB_0$ (one candidate USR) are presented for each SAR
in Tables \@ref(tab:ref-points-hg) through \@ref(tab:ref-points-wcvi).

The LRP and USR relate stock status to the DFO PA Framework [@dfo2009], and
in the assessment of Pacific Herring the same calculations are applied for each SAR.
There is an important distinction between reference points (e.g., LRP, USR) and
operational control points of the harvest control rule (HCR)
or the management procedure used to set catch limits.
Specifically, operational control points (OCPs) define the inflection points
of a HCR, and identify biomass levels where management action is taken.
For example, the harvest rate is set to zero and fishing ceases when
biomass falls below the lower OCP.

<!-- TODO: Not sure where to put this -->
Coast wide spawning biomass and catch is shown in
Figure \@ref(fig:coastwide-biomass-catch).
Total biomass and spawning biomass are shown in 
Figure \@ref(fig:biomass-total-biomass).

### Haida Gwaii

Estimated spawning biomass declined to near historic lows in the mid-1990s and
briefly increased through the late 1990s before falling to
persistent historic lows from 2000 to 2010 (Figure \@ref(fig:storyboard-hg)d).
A modest increase in estimated spawning biomass occurred during the early 2010s
before falling once again to near historic lows from 2016 to 2018.
The modest increase can be attributed to increases in the spawn index in
2013 and 2015 (Figure \@ref(fig:storyboard-hg)a) that were supported by
above average recruitment of age-`r age_first` fish in 2012
(Figure \@ref(fig:storyboard-hg)c, d).
An increasing trend in the estimated natural mortality rate since 1980
(Figure \@ref(fig:storyboard-hg)b) largely absorbed surplus production
attributable to above average recruitment events
(e.g., 1997 and 2012; Figure \@ref(fig:storyboard-hg)c, d).
Estimated natural mortality has increased sharply since the early 2010s
following a decline from a peak rate around 2002.
Since 2000, the HG stock has been in a low biomass state,
with many of these years also showing low productivity
which has precluded stock growth (Figure \@ref(fig:storyboard-hg)f).
There is an increase in survey biomass in 2019 and 2020, and
above-average recruitment of age-2s in 2018, and
below-average recruitment in 2019 and 2020.
In the most recent two years, between 2019 and 2020 and 2020 and 2021,
production is estimated to be neither positive nor negative
(i.e., production is 0),
preceded by two consecutive years of positive productivity.
Overall, biomass remains low relative to historical patterns and
natural mortality rates remain at historic high levels (up to 2016).
The most recent 3 years show a decline in estimated natural mortality,
responding to an increase in spawn biomass (2019-2021) and
below average recruitment (2019-2021).
The effective harvest rate $U_t$ since 2000 has been at or near zero
(Figure \@ref(fig:harvest-rate)),
with the last commercial roe fishery in 2002,
and the last commercial SOK fishery in 2004.

`r stock_status_text(SAR = "HG", this_yr = assess_yr, translate = french)`
Management measures to support long-term recovery of herring stocks in
Haida Gwaii are being developed through the rebuilding plan process
(Section "\nameref{sec:harv-opts}").

### Prince Rupert District

Estimated spawning biomass recovered by the mid-1980s from
historic low depletion levels following the collapse of the 1960s,
to about 50% of the historic high biomass estimated in the early 1960s
(Figure \@ref(fig:storyboard-prd)d).
However, after the mid-1980s,
estimated spawning biomass steadily declined before
stabilizing at a relatively low level (but above historic lows) by around 2005.
The estimated stock biomass has shown little trend from 2005 to 2018,
with a modest increase in 2019.
Survey biomass in 2020 is near-identical to that of 2019;
biomass increased again in 2021.
Fluctuations in the trend in spawning biomass appear to be less
than those observed in other SARs,
possibly because some spawn index points are being under- or over-fit
(e.g., 2001 to 2004, and 2010 to 2013)
as shown in Figure \@ref(fig:storyboard-prd)a.
Estimated natural mortality reached historic highs in the late 1960s,
before declining through the late 1970s.
Beginning in about 1980, estimated natural mortality increased through to 2005, 
roughly doubling from 0.25 to 0.5&nbsp;$\text{yr}^{-1}$ 
and then stabilized from 2005 to 2021 at a median rate of 0.45
(Figure \@ref(fig:storyboard-prd)b).
The trend in natural mortality from 1980 to 2005 coincides with
the decline in spawning biomass (Figure \@ref(fig:storyboard-prd)d),
during which recruitment deviations fluctuated around 0
without any strong positive or negative trends
(Figure \@ref(fig:storyboard-prd)e).
Above average age-`r age_first`+ recruitments in 2014, 2017 and 2018,
and an increase in the spawn index in the last three years
appears to be sufficient to lead to an increase in estimated spawning biomass
in 2019 through 2021, relative to 2018 (Figure \@ref(fig:storyboard-prd)f).
Commercial catches from 2007 to 2018 have remained low (below 2,000&nbsp;t) and
there was no commercial catch in 2019, 2020, or 2021.
The estimated natural mortality appears to be unchanged from last year,
resulting in what appears to be a small increase in production
between 2018 and 2019, sustaining the 2019 biomass increase through 2021.

`r stock_status_text(SAR = "PRD", this_yr = assess_yr, translate = french)`
Commercial fisheries have occurred annually in PRD since the mid-1980s,
with the exception of 2019 to 2021,
during which the effective harvest rate $U_t$ was estimated to be at or below 20% 
(Figure \@ref(fig:harvest-rate)) in all years except 1989.

### Central Coast

Estimated spawning biomass declined from a historic high around 1980
to historic low levels in the period of 2005 to 2015
(Figure \@ref(fig:storyboard-cc)d).
An increase in spawning stock biomass was estimated through the mid-2010s
but remained below levels estimated prior to 2000,
with survey biomass declining in 2017, 2018 and 2021.
In 2019 there was an increase in estimated spawning biomass,
with a similar level estimated for 2020.
The estimated biomass trend largely reflects the trend in the spawn index
(Figure \@ref(fig:storyboard-cc)a),
where fluctuations correspond opposite to the fluctuations in
estimated natural mortality (Figure \@ref(fig:storyboard-cc)b).
For example, the decline in spawn index (and estimated spawning biomass) to
the historic lows around 2008 followed an increasing trend in
estimated natural mortality through the same period.
Estimated natural mortality moderated around 2008,
which was followed by an increase in spawn index
(and estimated spawning biomass) 
until 2017 whereupon natural mortality ceased declining.
Recruitment deviations were slightly negative
(i.e., lower than predicted by the stock-recruit function)
on average from about 1990 to 2017,
and were above average in 2019 and 2020 (Figure \@ref(fig:storyboard-cc)e).
The model estimates very similar spawning biomass from 2019 through 2021
(Table \@ref(tab:cc-spawning-biomass-depletion)),
and the analysis of surplus production shows there is evidence of
strong production in the year between 2016/2017 and between 2018/2019,
similar to the 1990 to 1999 period (Figure \@ref(fig:storyboard-cc)f).
However, surplus production is estimated to be negative
in the years between 2019/2020 and 2020/2021.

An examination of spawn biomass by Herring Section shows
the recent decline in herring spawn to have largely occurred in
Spiller Channel (Sections 072 and 078) and
Kitasu Bay/East Higgins (Section 067; Figure \@ref(fig:spawn-section-cc)).
The majority of Area 07 spawn in 2021 appears concentrated in
Thompson/Stryker (Section 074).
Occurrence of spawn in Thompson/Stryker in 2020 and 2021
represents the first significant spawns for this section in many years.
The decline in spawn observations in 2020 and 2021 in Spiller Channel
(Sections 072 and 078) brings 
the spawn biomass in those Sections down to the low levels observed around 2010
(Figure \@ref(fig:storyboard-cc)d).
The mechanisms driving fluctuations of spawn throughout the Central Coast
are not well understood.

A fixed cutoff HCR was implemented in 1986, and
from 1986 to 2007 the effective harvest rate $U_t$ is estimated to fluctuate
above and below the `r target_hr*100`% target rate,
with median estimates exceeding `r target_hr*100`% frequently
(Figure \@ref(fig:harvest-rate)).
Occurrences of $U_t$ exceeding the `r target_hr*100`% target harvest rate
are due in part to positive assessment model errors, and
lags in detecting a directional change in the trend.

Following a commercial fishery closure from 2007 to 2013,
the CC stock reopened to commercial fisheries in 2014,
and small commercial roe fisheries occurred in 2014, 2015, and 2016.
A commercial SOK fishery operated yearly from 2014 to 2020,
however these removals are not included in the estimation of $U_t$. 
A commercial SOK fishery did not occur in Area 07 in 2020 due to COVID-19,
however it successfully resumed in 2021 (Table \@ref(tab:annual-sok-catch)).

`r stock_status_text(SAR = "CC", this_yr = assess_yr, translate = french)`

### Strait of Georgia

The estimated spawning biomass for the SoG stock
declined in 2019,
increased in 2020, and
declined in 2021.
Accordingly, the uncertainty associated with the last few years of spawning biomass
along with the forecast biomass `r paste0("$\\SB_{", assess_yr, "}$")`,
is quite large (Figure \@ref(fig:storyboard-sog)d).
There was an increasing trend in estimated spawning biomass
from about 2010 to 2016, which coincided with
a decline in estimated natural mortality that began in the late 2000s
(Figure \@ref(fig:storyboard-sog)b).
The model estimates natural mortality has been increasing since 2016,
and has now reached a level last estimated in the late 1960s.
This coincides with large shifts in survey biomass in the last five years,
with the index declining from 2016 to 2017, 2018 to 2019, and 2020 to 2021.
The large uncertainty in both spawning biomass and natural mortality estimates
in `r assess_yr` may be in part a function of the declining trend
in the spawn index starting in 2016 following the increasing trend that began in 2010 (Figure \@ref(fig:storyboard-sog)a).
The model fits an averaged trajectory through the spawn index values of the 2010s
and is currently underfitting the survey data from 2014 though 2016 and 2020.
The model estimates above average recruitment in most years from 2010 to
`r assess_yr` (Figure \@ref(fig:storyboard-sog)c),
with especially large positive deviations in 2019 and 2020
(Figure \@ref(fig:storyboard-sog)e).
The large uncertainty around estimated age-`r age_first` recruitment
in 2019 and 2020 was observed in the previous years' assessment and
remains apparent now that these age-2s are
fully recruited to the fishing/sampling gear.
Analysis of surplus production shows that for the year between 2019 and 2020,
the SoG SAR is estimated to be in a high production, high biomass state,
followed by negative production for the year between 2020 and 2021
(Figure \@ref(fig:storyboard-sog)f).

Commercial fisheries have occurred annually in SoG since the early-1970s
(following the stock collapse of the late 1960s).
Since implementing the fixed cutoff HCR in 1986,
the effective harvest rate $U_t$ is estimated to fluctuate
above and below the `r target_hr*100`% target rate,
with median estimates distributed evenly above and below `r target_hr*100`%
(Figure \@ref(fig:harvest-rate)).
The model estimates the median effective harvest rate exceeded 25% in 2006 and 2017.

`r stock_status_text(SAR = "SoG", this_yr = assess_yr, translate = french)`

### West Coast of Vancouver Island

The time series of estimated spawning biomass shows a decline
from the late 1980s through to a historic low in the 2000s
(Figure \@ref(fig:storyboard-wcvi)d).
The low estimated spawning biomass persisted through the 2006 to 2012 period
and has since slowly increased to a level similar to that estimated for 2000.
The model reconstruction of spawning biomass closely follows the trajectory
of spawn index values (Figure \@ref(fig:storyboard-wcvi)a).
Historically high natural mortality rates occur in the late 2000s and
have since declined, though show an increasing trend from 2015 to 2021
(Figure \@ref(fig:storyboard-wcvi)b).
Recruitment deviations have been negative
(i.e., lower than predicted by the stock-recruit function)
on average since about 2003 (Figure \@ref(fig:storyboard-wcvi)e),
with the exception of 2015, 2020 and 2021.
The reduction in estimated natural mortality below historical high levels and
absence of removals from a commercial fishery appear
to be sufficient to offset this below average recruitment of
age-`r age_first` fish to support biomass growth.
The absence of a commercial fishery since 2005 means the realized harvest rate
has been zero for the last 15 years (Figure \@ref(fig:harvest-rate)).
There is modest evidence for an increase in biomass above the LRP
since 2016 and
production estimates for the year between 2019 and 2020, and 2020 and 2021
are positive (Figure \@ref(fig:storyboard-wcvi)f).

Investigation of WCVI MCMC diagnostics revealed autocorrelation in the estimation of
fishery selectivity-at-50% ($\hat{a}_1$) 
and its standard deviation ($\hat{\gamma}_1$)
for the "other" fisheries category
(i.e., reduction, food and bait, as well as special use).
Autocorrelation in parameter estimation may indicate
bias in the posterior distribution or local minima. 
In this instance, autocorrelation likely resulting from
there being no new commercial fishery data since 2005. 
Running longer chains resulted in only minor improvements.
If and when fisheries resume in the future,
the addition of new fishery data may reduce this apparent autocorrelation and
any resulting bias.

`r stock_status_text(SAR = "WCVI", this_yr = assess_yr, translate = french)`

## Management performance

Management procedure performance can be investigated using
the time series of effective harvest rate $U$.
Estimated effective harvest rate $U$ in each year $t$ is
$U_t = C_t/(C_t + \SB_t)$, where
$C_t$ is catch in year $t$, and
$\SB_t$ is estimated spawning biomass in year $t$.
Time series of $U_t$ relative to
the target harvest rate of `r target_hr*100`%
are presented in Figure \@ref(fig:harvest-rate).

## Application of MPs and harvest options for `r assess_yr + 1`\label{sec:harv-opts}

Harvest options for `r assess_yr+1` reflect application of simulation-tested MPs
for each major SAR. 
MPs included for SoG and WCVI combines information from
the first MSE cycle [@dfo2019a] with
updated MP evaluations conducted in September 2020 [@dfo2021b].
MPs included for PRD and CC combines information from
the first MSE cycle for northern SARs [@dfo2019c] with
updated MP evaluations conducted in the summer of 2021 (this document).
Science advice in 2018 recommended
discontinuing the use of the historical fixed cutoff HCR [@dfo2019a];
as such this MP has been removed from further consideration
for all Pacific Herring SARs.
Finally, MPs are not provided for HG due to requirements
for a rebuilding plan (detailed below).

### Haida Gwaii

The HG stock persisted in a low biomass, low productivity state
from approximately 2000 to 2018.
The stock was below the LRP for much of that period and shows
little evidence of sustained stock growth despite the absence of
commercial fisheries since 2002 (and since 2004 for the SOK fishery).
Survey biomass increased in 2019 and 2020, however
biomass estimates are highly uncertain given persistent high natural mortality.
Results of the simulation-evaluations found that none of the proposed MPs, 
including the historical and no fishing MPs,
performed satisfactorily against the conservation objective of
maintaining spawning biomass above the LRP with high probability
[i.e., at least 75%, @dfo2009].\footnote{\label{fn:HighProb}``High'' probability is defined as 75 to 95\% by the DFO decision-making framework (DFO 2009).}

`r proj_biomass_text(SAR = "HG", next_yr = assess_yr + 1, translate = french)`

DFO has committed to developing and implementing a rebuilding plan for
Haida Gwaii Pacific Herring.
Work finalizing the draft for consultation continues via a 
technical working group comprised of members of
the Council of Haida Nation, DFO, and Parks Canada.
The consultation period is anticipated to commence in fall 2021.
Guidance for developing rebuilding plans [@dfo2013] states that
the primary objective of any rebuilding plan is to
promote stock growth out of the Critical Zone
(i.e., to grow the stock above the status-based LRP) by
ensuring removals from all fishing sources are kept to the lowest possible level
until the stock has cleared this zone with high probability.
Stock rebuilding does not end having met this goal, however, and
one of the goals of the rebuilding plan will be to
identify candidate threshold biomass levels greater than the LRP
that are consistent with a rebuilt state.

Based on MP evaluations and the ongoing rebuilding plan process,
the harvest recommendation for the HG stock in `r assess_yr + 1` is 0&nbsp;t.
Because Haida Gwaii has an on-going rebuilding plan process,
we did not update the HG OM with recent data
(as we did for PRD and CC; see below).

### Prince Rupert District

The PRD estimated stock biomass has shown little trend from 2005 to 2018,
with a modest increase from 2019 to 2021.

In the summer 2021, we updated the conditioning of the MSE operating model
for PRD with 2019 and 2020 spawn, catch, and biological data.
We re-ran MSE simulations to generate updated probability values for the MPs
presented in September 2019 [@dfo2020a] and 2020 [@dfo2021].
No new MPs or objectives were included.

The updated closed-loop feedback simulations for PRD show that
MPs with harvest rates at 5, 10, and 20% maintain spawning biomass
above the LRP with 78 to 100% probability, over all three OM scenarios
(Table \@ref(tab:decision-prd)). 

While MPs with harvest rates ranging from 5% to 20%
were able to meet the core conservation objective of
maintaining spawning biomass above the LRP with high probability
(i.e., at least 75%)^\ref{fn:HighProb}^,
they also imply different trade-offs among biomass (e.g., ecosystem)
and yield outcomes.
For management regions where multiple MPs meet the conservation objective,
further ranking of the remaining objectives is needed
in order to provide decision makers with a tractable set of trade-off choices.
However this was not undertaken because a fully specified set of objectives
has not yet been developed for each management area.

Effective harvest rates for the past 10 years (with positive catches)
average ~12% (Figure \@ref(fig:harvest-rate)),
during which the stock showed no sign of growth before 2018 and
is estimated to fluctuate at or near the LRP of $0.3\SB_0$
(Figure \@ref(fig:storyboard-prd)d). 
Spawning biomass depletion increased above $0.3\SB_0$ in 2019 and
remained above in 2020 and 2021.
Although there is not evidence of a low biomass and low productivity state
for PRD in the past 30-years, adjacent SARs (HG and CC)
show evidence of recent prolonged periods of low biomass and low productivity:
states that were entered rapidly and were preceded by high biomass levels
[@kronlund2017].

`r proj_biomass_text(SAR = "PRD", next_yr = assess_yr + 1, translate = french)`

Harvest options for `r assess_yr + 1`, resulting from simulation-tested MPs,
are presented in Table \@ref(tab:decision-prd),
and include probability values that reflect updated OM conditioning.

Relative to 2018 OM conditioning, the updated simulations show an improvement
in MP performance relative of the conservation objective,
driven by an increase in spawn index and lower
estimated natural mortality rates in the most recent years of the historical 
time series (up to 2020).
This outcome corroborates previous observations that MP evaluations appear
to be more heavily influenced by the last three to five years of
stock status and natural mortality trends used to condition the OM.

Harvest options listed in Table \@ref(tab:decision-prd) reflect
application of MPs to the `r assess_yr + 1` forecast biomass for PRD,
whereby each MP meets the conservation objective with a minimum 75% probability
under the Reference OM (i.e., DDM) scenario.
Harvest options under the two Robustness OM scenarios are also included.
For ease of comparison with MSE cycle 1 [@dfo2019c],
all MPs and scenarios listed in Table \@ref(tab:decision-prd)
include performance metrics for the four core objectives.

### Central Coast

The CC stock persisted in a low biomass, low productivity state from
approximately 2005 to 2014.
An increasing trend has been observed in recent years,
and overall the stock shows 
larger increases/decreases in spawn abundance
(Figure \@ref(fig:storyboard-cc)a) than was observed prior to 2005.

Similar to PRD, in the summer 2021 we updated the conditioning of the MSE 
operating model with 2019 and 2020 spawn, catch, and biological data. 
We re-ran MSE simulations to generate updated probability values for 
the MPs presented in September 2019 [@dfo2020a] and 2020 [@dfo2021].
No new MPs or objectives were included.

Management procedures, harvest options, and updated probabilities of 
obtaining objectives for 2022 under the three OM scenarios are presented 
in Table \@ref(tab:decision-cc). 
Harvest options listed in Table \@ref(tab:decision-cc) reflect application 
of MPs to the 2022 forecast biomass for CC, whereby each MP meets the 
conservation objective with a minimum 75% probability under the Reference OM 
(i.e., DDM) scenario.

Relative to 2018 OM conditioning, the updated simulations show an improvement
in MP performance of the conservation objective, driven by an increase in
estimated spawn index and lower estimated natural mortality rates in the 
most recent years of the time series (up to 2020).
This corroborates previous observations 
that MP evaluations seem more heavily influenced by the last three to five 
years of stock status and natural mortality trends.
Note this latest update does not include data from 2021, which show a decline in 
spawn index over the 2019 and 2020 observations (Figure \@ref(fig:storyboard-cc)a).

The updated simulations show that MPs with harvest rates at 5% and 10% 
maintain spawning biomass above the LRP with 84 to 100% probability over all 
three OM scenarios (Table \@ref(tab:decision-cc)).
Since multiple MPs meet the conservation objective of maintaining spawning 
biomass above the LRP with at least 75%, further ranking of the objectives 
provides decision makers with a tractable set of trade-off choices.
However this was not undertaken with the first MSE cycle because
a fully specified set of objectives has not yet been developed
for each management area.
Additionally, the current CC operating model is unable to directly address
Heilstuk Nation conservation objectives related to age and size of herring, nor 
objectives on a finer spatial scale or those specific to SOK fisheries.
These limitations exist for all five major stocks.

`r proj_biomass_text(SAR = "CC", next_yr = assess_yr + 1, translate = french)`

Finally, DFO acknowledges commitment to the Heiltsuk Nation for
the development of a Joint Fisheries Management Plan for Pacific Herring
in the Central Coast in `r assess_yr + 1`.
Results presented here may inform this on going commitment.

### Strait of Georgia

In 2018, closed-loop feedback simulations for the SoG showed that
all tested MPs could maintain the spawning biomass above the LRP
with 91% probability or higher across all OM scenarios. 

Additional simulation-evaluations were conducted in 2019 to
further explore the role of catch caps in
mitigating assessment errors [@dfo2019c].
A comparison of catch caps from 30,000&nbsp;t to 5,000&nbsp;t showed
no discernible gain in conservation performance under all 3 OM scenarios.
Results also showed MPs with catch caps of 20,000&nbsp;t or less
rarely exceed the 20% harvest rate for any given projection year
(over the 15 year projections).

In September 2020, the SoG OM was updated to include spawn survey data
from 2018 to 2020 and biological data for 2018 and 2019 [@dfo2021b].
The updated closed-loop feedback simulations for the SoG show that MPs
with harvest rates at 10, 15, and 20% maintain the spawning biomass
above the LRP with 75 to 85% probability over all three OM scenarios
(Table \@ref(tab:decision-sog)). 
MPs with harvest rate of 30% did not meet the conservation objective
($p$=69% for the Reference OM).

`r proj_biomass_text(SAR = "SoG", next_yr = assess_yr + 1, translate = french)`

Harvest options for `r assess_yr + 1`, resulting from simulation-tested MPs,
are presented in Table \@ref(tab:decision-sog).
These options reflect application of MPs to the `r assess_yr + 1`
forecast biomass for SoG,
whereby each MP meets the conservation objective with a minimum
75% probability under the Reference OM (DDM) scenario.
Harvest options under the two Robustness OM scenarios are also included.
All MPs and scenarios listed in Table \@ref(tab:decision-sog) include
updated performance metrics for the four core objectives
under all three scenarios [@dfo2021b].

In 2021, we investigated the sensitivity of SoG MP performance to changes in 
allocation of TAC between the roe seine and roe gillnet fleets.
The recent 20 year average catches show 
the food and bait, roe seine, and roe gillnet 
fleets take 21%, 40%, and 39% of the catch
and represents the status quo allocation used for this analysis.

We consider two changes in allocation of TAC between roe seine and roe gillnet fleets:
high gillnet allocation (i.e., 90% gillnet) and
high seine allocation (i.e., 90% seine).
MPs consider only movement between roe fleets,
thus no changes are made to the overall food and bait allocation.
Comparisons among TAC allocation are implemented using the HS30-60_HR20 MP
with an index based procedure.
This analysis was designed to investigate relative differences
between allocation MPs.
Thus we used an index-based approach in lieu of fitting the assessment model
to calculate the TAC for each simulated year, to save computational time.

Results show there is no difference in conservation performance
between simulated TAC allocation procedures (Table \@ref(tab:allocation-sog)).
That is, the simulations show that movement of TAC between
the roe fishery fleets
does not appear to impact the probability 
of avoiding the LRP over the 15-year simulation period.
Note that these results consider recent stock status of SoG herring, and
that due to structure of the current herring simulation model,
the simulation approach does not provide insight into 
year-to-year changes in age composition, spawn distribution, or spawning behaviour.
However, these results do indicate that given the overlap in catch at age 
between the two fleets, the harvest rates applied to the population and the 
age structure of the population, the differences in age and size selectivity 
between the two gears is not large enough to impact the status of the population.
Finally, probability values in Table \@ref(tab:allocation-sog)
should not be directly compared to those in Table \@ref(tab:decision-sog)
due to differences in assessment method implemented in the simulations
(index-based vs. current stock assessment model) and
the conditioning data used
(spawn survey data up to 2020 and biological data up to 2019 vs.
both spawn survey and biological data up to 2020).

### West Coast of Vancouver Island

The WCVI stock persisted in a low biomass, low productivity state from
approximately 2004 to 2014.
An increasing trend has been observed in recent years,
with biomass remaining low relative to historical levels,
trending around the LRP of $0.3\SB_0$.

In 2018, closed-loop feedback simulations for the WCVI showed
the conservation objective could be met under the Reference OM scenario
with between 75 and 87% probability,
but that these MPs failed to meet the conservation objective under the DIM
Robustness OM scenario, where natural mortality rates are
most similar to the last 10 years ($p=56$ to 74%).

In September 2020, the WCVI OM was updated to include
spawn survey data and biological data from 2018 to 2019 [@dfo2021b].
The updated closed-loop feedback simulations for the WCVI show that
MPs with harvest rates of 5, 10, and 15% maintained spawning biomass
above the LRP with between 81 and 93% probability,
over all three OM scenarios (Table \@ref(tab:decision-wcvi)). 
Improved MP performance in the 2020 update for WCVI,
relative to the first WCVI MSE cycle, 
is due to an increased spawn index in 2018 and 2019 and
increased status relative to $SB_0$. 
Performance improvement is observed under all three scenarios.

`r proj_biomass_text(SAR = "WCVI", next_yr = assess_yr + 1, translate = french)`

Harvest options for `r assess_yr + 1`, resulting from simulation-tested MPs,
are presented in Table \@ref(tab:decision-wcvi).
These options reflect application of MPs to the `r assess_yr + 1`
forecast biomass for WCVI,
whereby each MP meets the conservation objective with a minimum
75% probability under the Reference OM (DDM) scenario.
Harvest options under the two Robustness OM scenarios are also included.
All MPs and scenarios listed in Table \@ref(tab:decision-wcvi) include
updated performance metrics for the four core objectives
under all three scenarios [@dfo2021b].
